#!/usr/bin/env python3
"""Generate shared Reader settings and navigation metadata."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASE = ROOT / 'apps/mobile/shared/src/commonMain/kotlin/com/ermao/library/shared/modules/reader'
CATALOG = json.loads((Path(__file__).parent / 'reader-settings.json').read_text(encoding='utf-8'))
NAVIGATION_POLICY = json.loads((Path(__file__).parent / 'reader-navigation-policy.json').read_text(encoding='utf-8'))
CHECK = argparse.ArgumentParser()
CHECK.add_argument('--check', action='store_true')
CHECK = CHECK.parse_args().check

def write(path, content):
    if CHECK:
        if not path.exists() or path.read_text(encoding='utf-8') != content:
            raise SystemExit(f'Stale generated Reader contract: {path.relative_to(ROOT)}')
    else:
        path.write_text(content, encoding='utf-8')

def quote(value):
    return json.dumps(value, ensure_ascii=False)

rows = CATALOG['settings']
sections = {s['id']: s for s in CATALOG['sections']}
groups = CATALOG['optionGroups']
availability_reasons = CATALOG['availabilityReasons']
availability_rules = CATALOG['availabilityRules']
preference_version = CATALOG['preferenceVersion']
base_availability_checks = [
    ('!context.ready', '!ready', 'temporarilyUnavailable', 'TemporarilyUnavailable', 'engineNotReady'),
    ('context.nativeUnavailable?.has(setting.control)', 'control in nativeUnavailable', 'temporarilyUnavailable', 'TemporarilyUnavailable', 'publicationConstraint'),
    ('!context.supportedControls.has(setting.control)', 'control !in capabilities.supportedControls', 'notImplemented', 'NotImplemented', 'notImplemented'),
]
contextual_availability_checks = [
    ('wideViewport', '!context.wideViewport', '!wideViewport', 'temporarilyUnavailable', 'TemporarilyUnavailable', 'narrowViewport'),
    ('wakeLock', '!context.wakeLockSupported', '!wakeLockSupported', 'notImplemented', 'NotImplemented', 'wakeLockUnavailable'),
    ('zoom', '!context.canZoom', '!canZoom', 'notImplemented', 'NotImplemented', 'zoomUnavailable'),
    ('paginatedReflowable', "context.preferences.epub.flow === 'scrolled'", 'preferences.epub.flow == ReaderReadingMode.ContinuousScroll', 'temporarilyUnavailable', 'TemporarilyUnavailable', 'scrollingMode'),
    ('horizontalWritingMode', "context.preferences.epub.writingMode === 'vertical'", 'preferences.epub.writingMode == ReaderWritingMode.Vertical', 'temporarilyUnavailable', 'TemporarilyUnavailable', 'verticalWritingMode'),
    ('paginatedComic', "context.preferences.comic.flow === 'scrolled'", 'preferences.comic.flow == ReaderReadingMode.ContinuousScroll', 'temporarilyUnavailable', 'TemporarilyUnavailable', 'scrollingMode'),
    ('doubleComicSpread', "context.preferences.comic.spreadMode !== 'double'", 'preferences.comic.spreadMode != ReaderComicSpreadMode.Double', 'temporarilyUnavailable', 'TemporarilyUnavailable', 'requiresDoubleSpread'),
    ('optimizationEnabled', '!context.preferences.epub.optimization.enabled', '!preferences.epub.optimization.enabled', 'temporarilyUnavailable', 'TemporarilyUnavailable', 'optimizationDisabled'),
    ('publisherStylesOff', 'context.preferences.epub.typography.preservePublisherStyles', 'preferences.epub.typography.preservePublisherStyles', 'temporarilyUnavailable', 'TemporarilyUnavailable', 'publisherStylesActive'),
]
assert len({r['id'] for r in rows}) == len(rows)
for row in rows:
    assert row['section'] in sections
    assert row['options'] is None or row['options'] in groups
    assert row['label']['en-US'] and row['label']['zh-CN']
setting_ids = {row['id'] for row in rows}
for members in availability_rules.values():
    assert set(members) <= setting_ids
assert set(availability_rules) == {check[0] for check in contextual_availability_checks}
assert all(check[-1] in availability_reasons for check in base_availability_checks + contextual_availability_checks)

# iOS may rename native editable fields, but may not omit a catalog preference.
ios_binding = (ROOT / 'apps/mobile/iosApp/ErmaoLibrary/Features/Reader/IosReaderControlSession.swift').read_text(encoding='utf-8')
wire_fields = ios_binding.split('private static let wireFields:', 1)[1].split(']\n', 1)[0]
assert set(re.findall(r'"([a-zA-Z.]+)":', wire_fields)) == {r['path'] for r in rows if r['path']}
for row in rows:
    if row['limits'] is not None:
        minimum, maximum, step = row['limits']
        assert minimum < maximum and step > 0

runtime_catalog = {key: value for key, value in CATALOG.items() if key != 'preferenceVersion'}
ts = '// Generated by packages/reader-contracts/generate-reader-settings.py. Do not edit.\n'
ts += 'export const READER_SETTINGS_CATALOG = ' + json.dumps(runtime_catalog, ensure_ascii=False, indent=2) + ' as const;\n'


# Resolve domain types from their owner; no parallel handwritten preference model.
model = (BASE / 'domain/ReaderPreferences.kt').read_text(encoding='utf-8')
web_types = (ROOT / 'packages/reader-core/src/types.ts').read_text(encoding='utf-8')
web_preference_version = re.search(r'export const READER_PREFERENCES_VERSION = (\d+) as const;', web_types)
kmp_preference_version = re.search(r'const val SCHEMA_VERSION = (\d+)', model)
assert web_preference_version and int(web_preference_version.group(1)) == preference_version
assert kmp_preference_version and int(kmp_preference_version.group(1)) == preference_version
classes = {}
for name, body in re.findall(r'data class (\w+)\(\n(.*?)\n\)', model, re.S):
    classes[name] = dict(re.findall(r'val (\w+): (\w+)', body))
def field_type(path):
    current = 'ReaderPreferences'
    for part in path.split('.'):
        current = classes[current][part]
    return current

def copy_expression(parts, value, prefix='preferences'):
    field, *rest = parts
    replacement = copy_expression(rest, value, prefix+'.'+field) if rest else value
    return f'{prefix}.copy({field} = {replacement})'

ts += "\nexport type ReaderSettingId = typeof READER_SETTINGS_CATALOG.settings[number]['id'];\n"
ts += "export type ReaderControlId = NonNullable<typeof READER_SETTINGS_CATALOG.settings[number]['control']>;\n"
ts += "export type ReaderControlAvailability = 'available' | 'temporarilyUnavailable' | 'notImplemented' | 'notApplicable';\n"
ts += "export type ReaderAvailabilityReason = keyof typeof READER_SETTINGS_CATALOG.availabilityReasons;\n"
ts += "export type ReaderSettingAvailabilityContext = Readonly<{ morphology: 'reflowable' | 'comic' | 'pdf'; ready: boolean; supportedControls: ReadonlySet<string>; nativeUnavailable?: ReadonlySet<string>; wideViewport: boolean; wakeLockSupported: boolean; canZoom: boolean; preferences: ReaderPreferences }>;\n"
ts += "import { normalizeReaderPreferences } from './preferences';\nimport type { ReaderPreferences } from './types';\n"
ts += "export function readerSettingValue(preferences: ReaderPreferences, id: ReaderSettingId): string {\n  switch (id) {\n"
for row in rows:
    if row['path']: ts += f"    case {quote(row['id'])}: return String(preferences.{row['path']});\n"
ts += "    case 'reset': return '';\n  }\n}\n"
ts += "export function changeReaderSetting(preferences: ReaderPreferences, id: ReaderSettingId, value: string): ReaderPreferences {\n  switch (id) {\n"
def ts_copy(parts, value, prefix='preferences'):
    field, *rest = parts
    replacement = ts_copy(rest, value, prefix+'.'+field) if rest else value
    return '{ ...'+prefix+', '+field+': '+replacement+' }'
for row in rows:
    if not row['path']: continue
    typ = field_type(row['path'])
    value = 'value === \'true\'' if typ == 'Boolean' else 'Number(value)' if typ in ('Int','Double') else 'value'
    ts += f"    case {quote(row['id'])}: return normalizeReaderPreferences({ts_copy(row['path'].split('.'), value)});\n"
ts += "    case 'reset': return normalizeReaderPreferences({});\n  }\n}\n"
ts += '''export function readerSettingAvailability(id: ReaderSettingId, context: ReaderSettingAvailabilityContext): Readonly<{ availability: ReaderControlAvailability; reason?: ReaderAvailabilityReason }> {
  const setting = READER_SETTINGS_CATALOG.settings.find((candidate) => candidate.id === id);
  if (!setting || !(setting.formats as readonly string[]).includes(context.morphology)) return { availability: 'notApplicable' };
  if (setting.control === null) return { availability: 'available' };
  const rules = READER_SETTINGS_CATALOG.availabilityRules;
'''
for ts_condition, _, ts_availability, _, reason in base_availability_checks:
    ts += f"  if ({ts_condition}) return {{ availability: '{ts_availability}', reason: '{reason}' }};\n"
for rule, ts_condition, _, ts_availability, _, reason in contextual_availability_checks:
    ts += f"  if (rules.{rule}.includes(id as never) && {ts_condition}) return {{ availability: '{ts_availability}', reason: '{reason}' }};\n"
ts += "  return { availability: 'available' };\n}\n"
write(ROOT / 'packages/reader-core/src/setting-catalog.generated.ts', ts)

scroll_policy = NAVIGATION_POLICY['scrollPageTurn']
assert 0 < scroll_policy['viewportFraction'] <= 1
assert scroll_policy['boundaryEpsilonCssPixels'] >= 0

navigation_ts = f'''// Generated by packages/reader-contracts/generate-reader-settings.py. Do not edit.
import type {{ ReaderReadingProgression, ReaderWritingMode }} from './types';

export const READER_SCROLL_VIEWPORT_FRACTION = {scroll_policy['viewportFraction']} as const;
export const READER_SCROLL_BOUNDARY_EPSILON_CSS_PIXELS = {scroll_policy['boundaryEpsilonCssPixels']} as const;

export type ReaderPageTurnDirection = 'previous' | 'next';
export type ReaderPhysicalHorizontalSide = 'left' | 'right';

export function readerScrollAxis(writingMode: ReaderWritingMode) {{
  return writingMode === 'vertical' ? 'horizontal' : 'vertical';
}}

export function readerPhysicalHorizontalPageTurn(
  side: ReaderPhysicalHorizontalSide,
  readingProgression: ReaderReadingProgression
): ReaderPageTurnDirection {{
  if (readingProgression === 'rtl') return side === 'left' ? 'next' : 'previous';
  return side === 'left' ? 'previous' : 'next';
}}

export function readerAdjacentResourceProgression(direction: ReaderPageTurnDirection): 0 | 1 {{
  return direction === 'previous' ? 1 : 0;
}}
'''
write(ROOT / 'packages/reader-core/src/reader-navigation-policy.generated.ts', navigation_ts)

kt = '''// Generated by packages/reader-contracts/generate-reader-settings.py. Do not edit.
package com.ermao.library.shared.modules.reader.domain

data class ReaderSettingOption(val value: String, val key: String, val chinese: String, val english: String)
data class ReaderSettingSection(val id: String, val panel: String, val key: String, val chinese: String, val english: String, val advanced: Boolean)
data class ReaderAvailabilityReasonDefinition(val id: String, val key: String, val chinese: String, val english: String)
data class ReaderSettingDefinition(
    val id: String, val key: String, val section: String, val kind: String,
    val chinese: String, val english: String, val control: ReaderControl?,
    val formats: List<ReaderMorphology>, val options: List<ReaderSettingOption>,
    val minimum: Double, val maximum: Double, val step: Double, val availabilityRules: Set<String>,
) {
    fun value(preferences: ReaderPreferences): String = when (id) {
'''
for row in rows:
    if not row['path']: continue
    path = row['path']; typ = field_type(path)
    expr = f'preferences.{path}'
    expr += '.wireValue' if typ.startswith('Reader') else '.toString()'
    kt += f'        {quote(row["id"])} -> {expr}\n'
kt += '        else -> ""\n    }\n\n    @Throws(IllegalArgumentException::class)\n    fun change(preferences: ReaderPreferences, value: String): ReaderPreferences = when (id) {\n'
for row in rows:
    if not row['path']: continue
    path = row['path']; typ = field_type(path)
    expr = f'{typ}.entries.first {{ it.wireValue == value }}' if typ.startswith('Reader') else {'Int':'value.toInt()', 'Double':'value.toDouble()', 'Boolean':'value.toBooleanStrict()'}[typ]
    kt += f'        {quote(row["id"])} -> {copy_expression(path.split("."),expr)}\n'
kt += '''        "reset" -> resetReaderPreferences()
        else -> error("Unknown reader setting")
    }
}

data class ReaderSettingState(
    val availability: ReaderControlAvailability,
    val reasonId: String? = null,
)

object ReaderSettingsCatalog {
'''
kt_resolver = '''fun resolveReaderControl(
    control: ReaderControl,
    morphology: ReaderMorphology,
    capabilities: ReaderCapabilities,
    preferences: ReaderPreferences,
    ready: Boolean,
    nativeUnavailable: Set<ReaderControl> = emptySet(),
): ReaderControlAvailability {
    val definitions = settings.filter { it.control == control }
    val setting = definitions.firstOrNull { morphology in it.formats }
    if (setting == null && definitions.isNotEmpty()) return ReaderControlAvailability.NotApplicable
    return resolveReaderState(
        control,
        setting,
        capabilities,
        preferences,
        ready,
        nativeUnavailable,
    ).availability
}

fun resolveReaderSetting(
    setting: ReaderSettingDefinition,
    morphology: ReaderMorphology,
    capabilities: ReaderCapabilities,
    preferences: ReaderPreferences,
    ready: Boolean,
    nativeUnavailable: Set<ReaderControl> = emptySet(),
    wideViewport: Boolean = true,
    wakeLockSupported: Boolean = true,
    canZoom: Boolean = true,
): ReaderSettingState {
    if (morphology !in setting.formats) {
        return ReaderSettingState(ReaderControlAvailability.NotApplicable)
    }
    val control = setting.control ?: return ReaderSettingState(ReaderControlAvailability.Available)
    return resolveReaderState(
        control,
        setting,
        capabilities,
        preferences,
        ready,
        nativeUnavailable,
        wideViewport,
        wakeLockSupported,
        canZoom,
    )
}

private fun resolveReaderState(
    control: ReaderControl,
    setting: ReaderSettingDefinition?,
    capabilities: ReaderCapabilities,
    preferences: ReaderPreferences,
    ready: Boolean,
    nativeUnavailable: Set<ReaderControl>,
    wideViewport: Boolean = true,
    wakeLockSupported: Boolean = true,
    canZoom: Boolean = true,
): ReaderSettingState {
'''
for _, kt_condition, _, kt_availability, reason in base_availability_checks:
    kt_resolver += f'    if ({kt_condition}) return ReaderSettingState(ReaderControlAvailability.{kt_availability}, {quote(reason)})\n'
kt_resolver += '    val rules = setting?.availabilityRules.orEmpty()\n    return when {\n'
for rule, _, kt_condition, _, kt_availability, reason in contextual_availability_checks:
    kt_resolver += f'        {quote(rule)} in rules && {kt_condition} ->\n            ReaderSettingState(ReaderControlAvailability.{kt_availability}, {quote(reason)})\n'
kt_resolver += '''        else -> ReaderSettingState(ReaderControlAvailability.Available)
    }
}
'''
kt += '\n'.join('    ' + line if line else '' for line in kt_resolver.splitlines()) + '\n\n'
kt += '    val sections: List<ReaderSettingSection> = listOf(\n'
for s in sections.values():
    args = [s['id'],s['panel'],'reader.catalog.section.'+s['id'],s['label']['zh-CN'],s['label']['en-US']]
    kt += '        ReaderSettingSection('+', '.join(map(quote,args))+', '+str(s['advanced']).lower()+'),\n'
kt += '    )\n    val availabilityReasons: Map<String, ReaderAvailabilityReasonDefinition> = mapOf(\n'
for name, label in availability_reasons.items():
    kt += '        '+quote(name)+' to ReaderAvailabilityReasonDefinition('+', '.join(map(quote,[name,'reader.catalog.reason.'+name,label['zh-CN'],label['en-US']]))+'),\n'
kt += '    )\n    val settings: List<ReaderSettingDefinition> = listOf(\n'
forms = {'reflowable':'Reflowable','comic':'Comic','pdf':'Pdf'}
for row in rows:
    args = [row['id'],'reader.catalog.'+row['id'],row['section'],row['kind'],row['label']['zh-CN'],row['label']['en-US']]
    ctrl = 'ReaderControl.'+row['control'] if row['control'] else 'null'
    opts = ', '.join('ReaderSettingOption('+', '.join(map(quote,[o['value'],'reader.catalog.option.'+row['options']+'.'+o['value'],o['label']['zh-CN'],o['label']['en-US']]))+')' for o in groups.get(row['options'],[]))
    limits = row['limits'] or [0,0,0]
    rule_names = [name for name, members in availability_rules.items() if row['id'] in members]
    kt += '        ReaderSettingDefinition('+', '.join(map(quote,args))+', '+ctrl+', listOf('+', '.join('ReaderMorphology.'+forms[f] for f in row['formats'])+'), listOf('+opts+'), '+', '.join(str(float(v)) for v in limits)+', setOf('+', '.join(map(quote, rule_names))+')),\n'
kt += '    )\n}\n'
write(BASE / 'domain/ReaderSettingsCatalog.generated.kt', kt)

navigation_kt = f'''// Generated by packages/reader-contracts/generate-reader-settings.py. Do not edit.
package com.ermao.library.shared.modules.reader.domain

enum class ReaderPageTurnDirection {{ Previous, Next }}
enum class ReaderPhysicalHorizontalSide {{ Left, Right }}

object ReaderNavigationPolicy {{
    const val SCROLL_VIEWPORT_FRACTION: Double = {scroll_policy['viewportFraction']}
    const val SCROLL_BOUNDARY_EPSILON_CSS_PIXELS: Double = {scroll_policy['boundaryEpsilonCssPixels']}

    fun physicalHorizontalPageTurn(
        side: ReaderPhysicalHorizontalSide,
        readingProgression: ReaderReadingProgression,
    ): ReaderPageTurnDirection = when (readingProgression) {{
        ReaderReadingProgression.LeftToRight -> if (side == ReaderPhysicalHorizontalSide.Left) ReaderPageTurnDirection.Previous else ReaderPageTurnDirection.Next
        ReaderReadingProgression.RightToLeft -> if (side == ReaderPhysicalHorizontalSide.Left) ReaderPageTurnDirection.Next else ReaderPageTurnDirection.Previous
    }}

    fun adjacentResourceProgression(direction: ReaderPageTurnDirection): Double =
        if (direction == ReaderPageTurnDirection.Previous) 1.0 else 0.0
}}
'''
write(BASE / 'domain/ReaderNavigationPolicy.generated.kt', navigation_kt)

# iOS uses native localization lookup; these keys are generated, not separately authored.
resource = ROOT / 'apps/mobile/iosApp/ErmaoLibrary/Resources/Localizable.xcstrings'
localization = json.loads(resource.read_text(encoding='utf-8'))
strings = localization['strings']
for key in list(strings):
    if key.startswith('reader.catalog.') and key != 'reader.catalog.unavailable': del strings[key]
labels = [('reader.catalog.'+r['id'],r['label']) for r in rows]
labels += [('reader.catalog.section.'+s['id'],s['label']) for s in sections.values() if s['label']['zh-CN']]
labels += [('reader.catalog.option.'+name+'.'+o['value'],o['label']) for name,options in groups.items() for o in options]
labels += [('reader.catalog.reason.'+name,label) for name,label in availability_reasons.items()]
for key,label in labels:
    strings[key] = {'extractionState':'manual','localizations':{locale:{'stringUnit':{'state':'translated','value':label[source]}} for locale,source in [('en','en-US'),('zh-Hans','zh-CN')]}}
write(resource,json.dumps(localization,ensure_ascii=False,indent=2)+'\n')
