"""Generate Reader progress timing constants and shared timing test vectors."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HEADER = "// Generated by packages/reader-contracts/generate-reader-progress-timing.py. Do not edit."


def positive_integer(value: object) -> int:
    """Reject booleans and nonpositive timing values at the JSON boundary."""
    if type(value) is not int or value <= 0:
        raise ValueError("Expected a positive integer")
    return value


def read_object(path: Path, keys: set[str]) -> dict[str, object]:
    """Read only the explicitly supported version-one contract fields."""
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict) or set(value) != keys or value["version"] != 1:
        raise ValueError(f"Invalid version-one contract: {path.name}")
    positive_integer(value["version"])
    return value


def render_outputs(root: Path) -> dict[Path, str]:
    """Validate the single source and render production and test bindings."""
    contracts = root / "packages/reader-contracts"
    timing = read_object(
        contracts / "reader-progress-timing.json",
        {
            "version",
            "maxUnsavedIntervalMillis",
            "periodicCaptureIntervalMillis",
        },
    )
    maximum = positive_integer(timing["maxUnsavedIntervalMillis"])
    periodic = positive_integer(timing["periodicCaptureIntervalMillis"])
    if periodic >= maximum:
        raise ValueError("Periodic capture must leave time for durable persistence")
    ts = HEADER + "\nexport const READER_PROGRESS_TIMING = {\n"
    kt = HEADER + "\npackage com.ermao.library.shared.modules.reader\n\n"
    kt += "public object ReaderProgressTiming {\n"
    for key, value in timing.items():
        ts += f"  {key}: {value},\n"
        kt += f"    public const val {key}: Long = {value}L\n"
    outputs = {
        root / "packages/reader-core/src/reader-progress-timing.generated.ts": ts
        + "} as const;\n",
        root
        / (
            "apps/mobile/shared/src/commonMain/kotlin/com/ermao/library/shared/"
            "modules/reader/ReaderProgressTiming.generated.kt"
        ): kt + "}\n",
    }

    fixture = read_object(
        contracts / "fixtures/reader-progress-timing-v1.json",
        {
            "version",
            "positionStepMillis",
            "continuousCheckpointsMillis",
            "maxCaptureAgeMillis",
            "pauseAtMillis",
        },
    )
    step = positive_integer(fixture["positionStepMillis"])
    pause = positive_integer(fixture["pauseAtMillis"])
    age = positive_integer(fixture["maxCaptureAgeMillis"])
    checkpoints = fixture["continuousCheckpointsMillis"]
    if not isinstance(checkpoints, list) or not checkpoints:
        raise ValueError("Expected nonempty checkpoint list")
    points = [positive_integer(point) for point in checkpoints]
    if points != sorted(set(points)) or any(point % step for point in points):
        raise ValueError("Checkpoints must increase and align with engine steps")
    if age != maximum or pause >= periodic or pause % step:
        raise ValueError("Fixture must cover the maximum age and a pre-periodic pause")
    # Common tests have no filesystem API. Generate the same small test vector
    # for both test source sets instead of adding a platform loader or runtime API.
    for directory, package in (
        (
            "shared/src/commonTest/kotlin/com/ermao/library/shared/modules/audio",
            "com.ermao.library.shared.modules.audio",
        ),
        (
            "androidApp/src/test/kotlin/com/ermao/library/features/audio/application",
            "com.ermao.library.features.audio.application",
        ),
    ):
        vector = HEADER + f"\npackage {package}\n\n"
        vector += "internal object ReaderProgressTimingFixture {\n"
        vector += f"    const val positionStepMillis: Long = {step}L\n"
        vector += "    val continuousCheckpointsMillis: List<Long> = listOf("
        vector += ", ".join(f"{point}L" for point in points) + ")\n"
        vector += f"    const val maxCaptureAgeMillis: Long = {age}L\n"
        vector += f"    const val pauseAtMillis: Long = {pause}L\n}}\n"
        outputs[
            root
            / "apps/mobile"
            / directory
            / "ReaderProgressTimingFixture.generated.kt"
        ] = vector
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    for path, expected in render_outputs(root).items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                raise SystemExit(
                    f"Stale Reader progress timing binding: {path.relative_to(root)}"
                )
        else:
            path.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
