"""Generate native Reader HTTP error constants from the authoritative JSON."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def render_contract(value: object, *, reader_safety_error_codes: set[str]) -> str:
    """Validate the wire contract before generating Kotlin constants."""
    if not isinstance(value, dict) or set(value) != {"publication", "comic"}:
        raise ValueError("Expected publication and comic error groups")
    lines = [
        "// Generated by packages/reader-contracts/generate-reader-http-errors.py. Do not edit.",
        "package com.ermao.library.shared.modules.reader.infrastructure",
        "",
        "import com.ermao.library.shared.modules.reader.domain.ReaderSafetyErrorCode",
        "",
        "internal object ReaderHttpErrorStatuses {",
    ]
    for group, codes in value.items():
        if not isinstance(codes, dict) or not codes:
            raise ValueError("Expected nonempty error group")
        lines.append(f"    val {group}: Map<String, Set<Int>> = mapOf(")
        for code, statuses in codes.items():
            if not isinstance(code, str) or not re.fullmatch(
                r"[A-Z][A-Z0-9_]{0,63}", code
            ):
                raise ValueError("Invalid Reader error code")
            if (
                not isinstance(statuses, list)
                or not statuses
                or any(
                    type(status) is not int or not 400 <= status <= 599
                    for status in statuses
                )
                or len(set(statuses)) != len(statuses)
            ):
                raise ValueError("Invalid Reader error HTTP statuses")
            key = (
                f"ReaderSafetyErrorCode.{code}.name"
                if code in reader_safety_error_codes
                else f'"{code}"'
            )
            lines.append(f'        {key} to setOf({", ".join(map(str, statuses))}),')
        lines.append("    )")
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    source = root / "packages/reader-contracts/reader-http-error-statuses.json"
    safety_policy = root / "packages/reader-contracts/reader-safety-policy.json"
    target = root / (
        "apps/mobile/shared/src/commonMain/kotlin/com/ermao/library/shared/"
        "modules/reader/infrastructure/ReaderHttpErrorStatuses.kt"
    )
    safety_value = json.loads(safety_policy.read_text(encoding="utf-8"))
    safety_error_codes = {
        rule["errorCode"]
        for rule in safety_value["rules"]
        if rule["errorCode"] is not None
    } | set(safety_value["implementationFailureCodes"])
    expected = render_contract(
        json.loads(source.read_text(encoding="utf-8")),
        reader_safety_error_codes=safety_error_codes,
    )
    if args.check:
        if target.read_text(encoding="utf-8") != expected:
            raise SystemExit("Reader HTTP error contract is stale; run the generator.")
    else:
        target.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
