/* Generated by packages/reader-contracts/generate-reader-safety-policy.py. Do not edit. */
#ifndef ERMAO_READER_SAFETY_POLICY_GENERATED_H
#define ERMAO_READER_SAFETY_POLICY_GENERATED_H

#include <string.h>

#define ERMAO_READER_SAFETY_POLICY_DIGEST "12f3e2ba610d907fa4ca5eefd0ab2319e000a8b5348c45549c9e2bc721579a46"
#define ERMAO_READER_SAFETY_COMIC_PAGE_MAX_COUNT 10000LL
#define ERMAO_READER_SAFETY_COMIC_PAGE_MAX_BYTES 33554432LL
#define ERMAO_READER_SAFETY_COMIC_EXPANDED_MAX_BYTES 2147483648LL
#define ERMAO_READER_SAFETY_COMIC_COMPRESSION_RATIO_MAX 200LL

static inline int ermao_reader_safety_comic_extension_allowed(const char *extension) {
    if (extension == NULL) return 0;
    return strcmp(extension, "gif") == 0 ||
        strcmp(extension, "jpeg") == 0 ||
        strcmp(extension, "jpg") == 0 ||
        strcmp(extension, "png") == 0 ||
        strcmp(extension, "webp") == 0;
}

#endif
