export type ReadingFormat = 'COMIC' | 'EPUB' | 'PDF' | 'AUDIO' | 'MOBI' | 'AZW' | 'AZW3' | 'PRC' | 'FB2' | 'TXT';
export type MediaKind = 'EBOOK' | 'COMIC' | 'AUDIOBOOK';
export type WorkDetailTabKey = MediaKind | 'STRUCTURE';
export type ReadingStatus = 'UNREAD' | 'READING' | 'FINISHED';
export type PublicationStatus = 'UNKNOWN' | 'ONGOING' | 'COMPLETED' | 'HIATUS' | 'CANCELLED';
export type TrackingStatus = 'NOT_TRACKING' | 'TRACKING' | 'PAUSED' | 'IGNORED';

export type WorkDetailTab = {
  key: WorkDetailTabKey;
  label: string;
  sortOrder: number;
};

export type WorkMediaGroup = {
  kind: MediaKind;
  primaryEditionId: string | null;
  recentEditionId: string | null;
  recentVolumeId: string | null;
  status: ReadingStatus;
  progress: number;
  positionLabel: string;
  durationMs: number | null;
  chapterCount: number | null;
  volumeCount: number;
  editions: WorkView['editions'];
};

export type WorkView = {
  id: string;
  workId: string;
  editionId: string | null;
  monitorFolderId: string | null;
  title: string;
  author: string;
  publisher: string | null;
  type: 'ebook' | 'comic' | 'audiobook';
  mediaKind?: MediaKind;
  formatValue: ReadingFormat;
  format: string;
  size: string;
  progress: number;
  progressExtra?: Record<string, unknown>;
  currentHref?: string | null;
  currentSectionIndex?: number | null;
  currentChapterTitle?: string | null;
  currentChapterSortOrder?: number | null;
  statusValue: ReadingStatus;
  status: string;
  publicationStatusValue: PublicationStatus;
  publicationStatus: string;
  trackingStatusValue: TrackingStatus;
  trackingStatus: string;
  localLatestVolume: number | null;
  localLatestChapter: number | null;
  localLatestTitle: string | null;
  localLatestAt: string | null;
  ignored: boolean;
  organized: boolean;
  organizeStatus: string;
  metadataQuality: number;
  tags: string[];
  seriesName: string | null;
  seriesIndex: number | null;
  publishedYear: number | null;
  added: string;
  lastRead: string;
  lastReadAt: string | null;
  chapter: string;
  chapterCount: number | null;
  pageCount: number | null;
  desc: string;
  path: string;
  fileHash: string;
  gradient: string;
  coverStatus: string;
  coverUrl: string;
  totalUnits: number;
  readingProgress: number;
  durationMs?: number | null;
  narrator?: string | null;
  trackCount?: number | null;
  importStatus: string;
  importError: string | null;
  importedAt: string;
  files: Array<{
    id: string;
    editionId: string;
    volumeId: string | null;
    path: string;
    mimeType: string;
    kind: string;
    sortOrder: number;
    sizeBytes: number;
    size: string;
    durationMs?: number | null;
    codec?: string | null;
    bitrate?: number | null;
    sampleRate?: number | null;
    channels?: number | null;
    discNumber?: number | null;
    trackNumber?: number | null;
    url?: string;
  }>;
  versionCount: number;
  volumeCount: number;
  primaryEditionId: string | null;
  primaryEditionName: string | null;
  recentEditionId: string | null;
  recentVolumeId: string | null;
  availableMediaKinds?: MediaKind[];
  defaultMediaKind?: MediaKind | null;
  mediaGroups?: WorkMediaGroup[];
  detailTabs?: WorkDetailTab[];
  selectedDetailTab?: WorkDetailTabKey;
  volumes: Array<{
    id: string;
    editionId: string;
    title: string;
    volumeIndex: number | null;
    sortOrder: number;
    pageCount: number | null;
    chapterCount: number | null;
    coverUrl: string;
    progress?: number;
    progressExtra?: Record<string, unknown>;
    lastReadAt?: string | null;
    position?: string | null;
    currentPage?: number | null;
    currentHref?: string | null;
    currentSectionIndex?: number | null;
    currentChapterTitle?: string | null;
    currentChapterSortOrder?: number | null;
    durationMs?: number | null;
  }>;
  editions: Array<{
    id: string;
    workId: string;
    formatValue: ReadingFormat;
    mediaKind?: MediaKind;
    format: string;
    versionName: string;
    description?: string | null;
    publisher?: string | null;
    publishedAt?: string | null;
    language?: string | null;
    identifier?: string | null;
    isbn?: string | null;
    origin?: string | null;
    sourcePath?: string | null;
    primary: boolean;
    hidden: boolean;
    readable: boolean;
    conversionAvailable: boolean;
    size: string;
    pageCount: number | null;
    chapterCount: number | null;
    durationMs?: number | null;
    narrator?: string | null;
    trackCount?: number | null;
    abridged?: boolean | null;
    progress: number;
    lastReadAt: string | null;
    coverUrl: string;
    conversion?: {
      sourceFormat: string;
      targetFormat: string;
      converter: string;
      converterVersion: string | null;
      cached: boolean;
    } | null;
    files: WorkView['files'];
    volumes: WorkView['volumes'];
  }>;
};

export type SeriesSummary = {
  name: string;
  bookCount: number;
  latestUpdatedAt: string | null;
};
