import Foundation
@preconcurrency import ErmaoShared

extension SharedAdministrativeSettingsClient {
    nonisolated func value<Value>(_ result: any ErmaoShared.AdministrativeSettingsResult) throws -> Value {
        if let failure = result as? ErmaoShared.AdministrativeSettingsResultFailure { throw mapError(failure.error) }
        guard let content = result as? ErmaoShared.AdministrativeSettingsResultContent<AnyObject>, let value = content.value as? Value else { throw protocolFailure() }
        return value
    }
    nonisolated func protocolFailure() -> AdministrativeFailure { AdministrativeFailure(kind: .protocolViolation, code: "INVALID_RESPONSE") }
    nonisolated func mapError(_ value: ErmaoShared.AdministrativeSettingsError) -> AdministrativeFailure {
        let kind: AdministrativeFailureKind
        switch value.kind.name { case "Validation": kind = .validation; case "Unauthorized": kind = .unauthorized; case "Forbidden": kind = .forbidden; case "NotFound": kind = .notFound; case "Conflict": kind = .conflict; case "Unavailable", "Server", "RateLimited": kind = .unavailable; case "Transport": kind = .transport; default: kind = .protocolViolation }
        return AdministrativeFailure(kind: kind, code: value.code, fields: value.fieldViolations.map { AdministrativeFieldViolation(field: $0.field, code: $0.code) })
    }
    nonisolated func date(_ value: String?) -> Date? { guard let value else { return nil }; return ISO8601DateFormatter().date(from: value) }
    nonisolated func date(epoch: KotlinLong?) -> Date? { epoch.map { Date(timeIntervalSince1970: Double($0.int64Value) / 1000) } }
    nonisolated func data(_ bytes: KotlinByteArray) -> Data { Data((0..<Int(bytes.size)).map { UInt8(bitPattern: bytes.get(index: Int32($0))) }) }

    nonisolated func map(_ value: ErmaoShared.KindleSettings) -> KindleSettings { KindleSettings(recipient: value.recipientEmail, smtpConfigured: value.smtpConfigured, senderEmail: value.senderEmail) }
    nonisolated func map(_ value: ErmaoShared.SmtpSettings) -> SMTPSettings { SMTPSettings(host: value.host, port: Int(value.port), encryption: map(value.security), senderEmail: value.fromEmail, username: value.username, senderName: value.fromName, maximumAttachmentMegabytes: value.maximumAttachmentMegabytes?.doubleValue, hasPassword: value.passwordConfigured, replacementPassword: "") }
    nonisolated func map(_ value: ErmaoShared.SmtpSecurity) -> SMTPEncryption { switch value.name { case "Ssl": .tls; case "None": .none; default: .startTLS } }
    nonisolated func map(_ value: SMTPEncryption) -> ErmaoShared.SmtpSecurity { switch value { case .tls: .ssl; case .none: .none; case .startTLS: .starttls } }
    nonisolated func smtpUpdate(_ value: SMTPSettings) -> ErmaoShared.SmtpSettingsUpdate { ErmaoShared.SmtpSettingsUpdate(host: value.host, port: Int32(value.port), security: map(value.encryption), username: value.username, password: value.replacementPassword.isEmpty ? nil : value.replacementPassword, fromEmail: value.senderEmail, fromName: value.senderName, maximumAttachmentMegabytes: value.maximumAttachmentMegabytes.map(KotlinDouble.init(double:)), clearPassword: false) }
    nonisolated func map(_ value: KindleTaskStatus?) -> ErmaoShared.KindleTaskStatus? { guard let value else { return nil }; switch value { case .queued: return ErmaoShared.KindleTaskStatus.queued; case .sending: return ErmaoShared.KindleTaskStatus.sending; case .sent: return ErmaoShared.KindleTaskStatus.sent; case .failed: return ErmaoShared.KindleTaskStatus.failed; case .cancelled: return ErmaoShared.KindleTaskStatus.cancelled } }
    nonisolated func map(_ value: ErmaoShared.KindleTask) -> KindleSendTask { KindleSendTask(id: value.id, title: value.bookTitle, recipientMasked: mask(email: value.recipientEmail), status: map(value.status), progress: value.status == .sending ? 0.5 : nil, createdAt: date(value.createdAt) ?? .distantPast, errorCode: value.errorMessage) }
    nonisolated func map(_ value: ErmaoShared.KindleTaskStatus) -> KindleTaskStatus { switch value.name { case "Queued": .queued; case "Sending": .sending; case "Sent": .sent; case "Failed": .failed; default: .cancelled } }
    nonisolated func mask(email: String) -> String { guard let at = email.firstIndex(of: "@") else { return email }; let local = email[..<at]; return String(local.prefix(2)) + "****" + email[at...] }

    nonisolated func map(_ value: ErmaoShared.ManagedUser) -> AdministrativeUser { AdministrativeUser(id: value.id, displayName: value.name, email: value.email, role: value.role == .admin ? .administrator : .member, enabled: value.status == .active, canManageSystem: value.canManageSystem, libraryIDs: Set(value.libraryIds), canViewManualImports: value.canViewManualImports, locale: map(value.locale)) }
    nonisolated func map(_ value: UserRole) -> ErmaoShared.ManagedUserRole { value == .administrator ? .admin : .member }
    nonisolated func map(_ value: ErmaoShared.ManagedLocale) -> AdministrativeSettingsLocale { value == .enus ? .enUS : .zhCN }
    nonisolated func map(_ value: AdministrativeSettingsLocale) -> ErmaoShared.ManagedLocale { value == .enUS ? .enus : .zhcn }
    nonisolated func userUpdate(draft: UserDraft, existing: AdministrativeUser) -> ErmaoShared.UpdateManagedUser { ErmaoShared.UpdateManagedUser(name: draft.displayName, email: draft.email, role: map(draft.role), status: draft.enabled ? .active : .disabled, canManageSystem: draft.canManageSystem, canViewManualImports: existing.canViewManualImports, libraryIds: Array(existing.libraryIDs), locale: map(draft.locale)) }

    nonisolated func map(_ value: ErmaoShared.Library) -> LibrarySource { LibrarySource(id: value.id, displayName: value.name, serverPath: value.rootPath, enabled: value.enabled, organizationMode: map(value.organizationMode), ignorePatterns: value.ignorePatterns ?? "", ignoreHidden: value.ignoreHidden, minimumFileSizeBytes: value.minimumFileSizeBytes, description: value.description_ ?? "") }
    nonisolated func map(_ value: ErmaoShared.LibraryOrganizationMode) -> LibraryOrganizationMode { switch value.name { case "Volumes": .volumes; case "Audiobook": .audiobook; default: .flat } }
    nonisolated func map(_ value: LibraryOrganizationMode) -> ErmaoShared.LibraryOrganizationMode { switch value { case .flat: .flat; case .volumes: .volumes; case .audiobook: .audiobook } }
    nonisolated func map(_ value: ErmaoShared.MediaKindPolicy) -> MediaKind? { switch value.name { case "Ebook": .ebook; case "Comic": .comic; case "Audiobook": .audiobook; default: nil } }
    nonisolated func map(_ value: MediaKind?) -> ErmaoShared.MediaKindPolicy { guard let value else { return .mixed }; switch value { case .ebook: return ErmaoShared.MediaKindPolicy.ebook; case .comic: return ErmaoShared.MediaKindPolicy.comic; case .audiobook: return ErmaoShared.MediaKindPolicy.audiobook } }
    nonisolated func sourceDraft(_ value: LibrarySource) -> ErmaoShared.LibraryDraft { ErmaoShared.LibraryDraft(rootPath: value.serverPath, name: value.displayName, organizationMode: map(value.organizationMode), enabled: value.enabled, ignorePatterns: value.ignorePatterns.isEmpty ? nil : value.ignorePatterns, ignoreHidden: value.ignoreHidden, minimumFileSizeBytes: value.minimumFileSizeBytes, description: value.description.isEmpty ? nil : value.description) }
    nonisolated func map(_ value: ErmaoShared.DirectoryNode) -> ServerDirectoryPage { let parent = URL(fileURLWithPath: value.path).deletingLastPathComponent().path; let entries = ([ServerDirectoryEntry(name: "..", absolutePath: parent, modifiedAt: nil, isParent: true)] + value.children.filter(\.readable).map { ServerDirectoryEntry(name: $0.name, absolutePath: $0.path, modifiedAt: nil, isParent: false) }); return ServerDirectoryPage(currentPath: value.path, breadcrumbs: [], directories: entries) }
    nonisolated func map(_ value: ErmaoShared.ImportScanJob) -> DirectoryScanProgress { DirectoryScanProgress(path: value.rootPath, processed: Int(value.filesScanned), discovered: nil, bytesPerSecond: nil, canCancel: value.status == .pending || value.status == .running) }

    nonisolated func mapScan(_ value: ErmaoShared.ImportScanJob) -> ImportScanJob { ImportScanJob(id: value.id, path: value.rootPath, status: map(value.status), directoriesScanned: Int(value.directoriesScanned), filesScanned: Int(value.filesScanned), candidatesFound: Int(value.candidatesFound), queuedCount: Int(value.queuedCount), errorCount: Int(value.errorCount)) }
    nonisolated func map(_ value: ErmaoShared.ImportScanStatus) -> ImportScanStatus { switch value.name { case "Pending": .pending; case "Running": .running; case "Completed": .completed; case "Failed": .failed; default: .cancelled } }
    nonisolated func map(_ value: ErmaoShared.ImportPreferences) -> ImportPreferences { ImportPreferences(allowedExtensions: value.allowedExtensions, ignorePatterns: value.ignorePatterns) }
    nonisolated func map(_ value: ImportPreferences) -> ErmaoShared.ImportPreferences { ErmaoShared.ImportPreferences(allowedExtensions: value.allowedExtensions, ignorePatterns: value.ignorePatterns) }

    nonisolated func map(_ value: OrganizeJobStatus?) -> ErmaoShared.OrganizeStatusCategory? { guard let value else { return nil }; switch value { case .organized: return ErmaoShared.OrganizeStatusCategory.success; case .failed: return ErmaoShared.OrganizeStatusCategory.failed; case .pendingRecognition: return ErmaoShared.OrganizeStatusCategory.waiting; case .needsConfirmation: return ErmaoShared.OrganizeStatusCategory.recognizing; case .cancelled: return nil } }
    nonisolated func map(_ value: ErmaoShared.OrganizeJob) -> OrganizeJob { OrganizeJob(id: value.id, title: value.book.title, subtitle: value.book.author, status: map(value.statusCategory), errorCode: value.issueCodes.first) }
    nonisolated func map(_ value: ErmaoShared.OrganizeStatusCategory) -> OrganizeJobStatus { switch value.name { case "Success": .organized; case "Failed": .failed; case "Recognizing": .needsConfirmation; default: .pendingRecognition } }
    nonisolated func map(_ value: ErmaoShared.OrganizeRun) -> OrganizeRun { OrganizeRun(id: value.id, status: value.status, queuedCount: Int(value.queuedCount), completedCount: Int(value.completedCount), reviewCount: Int(value.reviewCount), failedCount: Int(value.failedCount), startedAt: date(value.startedAt), finishedAt: date(value.finishedAt)) }
    nonisolated func map(_ value: ErmaoShared.OrganizePolicy, queue: ErmaoShared.OpfQueueStatus) -> RecognitionPolicy { RecognitionPolicy(scheduled: value.enabled, schedule: mapSchedule(value.intervalMinutes, enabled: value.scheduleMode == .interval), runAfterImport: value.autoRunOnNew, persistToOPF: value.writeMetadataToFiles, localMetadataFirst: value.preferLocalMetadata, priorities: value.localMetadataPriority.compactMap(map), recognizeUnmatched: value.rules.unrecognized, recognizeMissingAuthorOrCover: value.rules.missingMetadata, eligibleCount: 0, nextRunAt: date(value.nextRunAt), opfQueueCompleted: max(0, Int(queue.capacity) - Int(queue.pendingTargets)), opfQueueTotal: Int(queue.capacity)) }
    nonisolated func mapSchedule(_ minutes: Int32, enabled: Bool) -> RecognitionSchedule { guard enabled else { return .manual }; if minutes <= 60 { return .hourly }; if minutes <= 360 { return .sixHours }; return .daily }
    nonisolated func map(_ value: ErmaoShared.LocalMetadataSource) -> MetadataPriority? { switch value.name { case "SidecarOpf": .opf; case "Embedded": .embedded; case "Path": .pathAndFilename; default: nil } }
    nonisolated func map(_ value: MetadataPriority) -> ErmaoShared.LocalMetadataSource { switch value { case .opf: .sidecaropf; case .embedded: .embedded; case .pathAndFilename: .path } }
    nonisolated func map(_ value: RecognitionPolicy, onto current: ErmaoShared.OrganizePolicy) -> ErmaoShared.OrganizePolicy { let minutes: Int32 = switch value.schedule { case .hourly: 60; case .sixHours: 360; case .daily: 1_440; case .manual: current.intervalMinutes }; return ErmaoShared.OrganizePolicy(id: current.id, enabled: value.scheduled, scheduleMode: value.schedule == .manual ? .manual : .interval, intervalMinutes: minutes, autoRunOnNew: value.runAfterImport, autoRunOnNewSince: current.autoRunOnNewSince, rules: ErmaoShared.OrganizeRules(unrecognized: value.recognizeUnmatched, missingMetadata: value.recognizeMissingAuthorOrCover), writeMetadataToFiles: value.persistToOPF, preferLocalMetadata: value.localMetadataFirst, localMetadataPriority: value.priorities.map(map), lastScheduledAt: current.lastScheduledAt, nextRunAt: current.nextRunAt, updatedAt: current.updatedAt) }

    nonisolated func map(_ value: ErmaoShared.LibraryOperation) -> LibraryOperation { LibraryOperation(id: value.id, action: value.action, status: value.status, summary: value.summary, createdAt: date(value.createdAt), undoAvailable: value.undoAvailable) }
    nonisolated func map(_ value: CategoryKind) -> ErmaoShared.CategoryKind { switch value { case .author: .author; case .tag: .tag; case .series: .series } }
    nonisolated func map(_ value: ErmaoShared.CategoryKind) -> CategoryKind { switch value.name { case "Author": .author; case "Tag": .tag; default: .series } }
    nonisolated func map(_ value: ErmaoShared.LibraryCategory) -> GovernedCategory { GovernedCategory(id: value.id, kind: map(value.kind), name: value.name, aliases: value.aliases, bookCount: Int(value.bookCount)) }

    nonisolated func map(_ value: ErmaoShared.MetadataProvider) -> MetadataProvider { MetadataProvider(id: value.id, displayName: value.name, enabled: value.enabled, status: value.lastTestStatus?.lowercased() == "ok" ? .available : value.lastTestStatus == nil ? .untested : .unavailable, responseMilliseconds: nil, supportedMediaKinds: Set(value.mediaKinds.map(map)), hasSecret: value.configuredSecrets.values.contains { $0.boolValue }, priority: Int(value.priority)) }
    nonisolated func map(_ value: ErmaoShared.MediaKind) -> MediaKind { switch value.name { case "Ebook": .ebook; case "Comic": .comic; default: .audiobook } }
    nonisolated func map(_ value: MediaKind) -> ErmaoShared.MediaKind { switch value { case .ebook: .ebook; case .comic: .comic; case .audiobook: .audiobook } }
    nonisolated func mapConfiguration(_ value: ErmaoShared.MetadataProvider) -> MetadataProviderConfiguration { var values = value.config.mapValues(map); for field in value.configFields where values[field.key] == nil { values[field.key] = map(field.defaultValue) }; return MetadataProviderConfiguration(provider: map(value), values: values, secretReplacements: [:], clearedSecretKeys: []) }
    nonisolated func map(_ value: any ErmaoShared.ProviderSettingValue) -> ProviderEditableValue { if let typed = value as? ErmaoShared.ProviderSettingValueText { return .text(typed.value) }; if let typed = value as? ErmaoShared.ProviderSettingValueToggle { return .toggle(typed.value) }; if let typed = value as? ErmaoShared.ProviderSettingValueInteger { return .integer(typed.value) }; if let typed = value as? ErmaoShared.ProviderSettingValueDecimal { return .decimal(typed.value) }; if let typed = value as? ErmaoShared.ProviderSettingValueTextList { return .textList(typed.value) }; return .empty }
    nonisolated func map(_ value: ProviderEditableValue) -> any ErmaoShared.ProviderSettingValue { switch value { case let .text(value): ErmaoShared.ProviderSettingValueText(value: value); case let .toggle(value): ErmaoShared.ProviderSettingValueToggle(value: value); case let .integer(value): ErmaoShared.ProviderSettingValueInteger(value: value); case let .decimal(value): ErmaoShared.ProviderSettingValueDecimal(value: value); case let .textList(value): ErmaoShared.ProviderSettingValueTextList(value: value); case .empty: ErmaoShared.ProviderSettingValueEmpty.shared } }
    nonisolated func map(_ value: MetadataProviderConfiguration) -> ErmaoShared.MetadataProviderUpdate { var values = value.values.mapValues(map); for (key, replacement) in value.secretReplacements where !replacement.isEmpty { values[key] = ErmaoShared.ProviderSettingValueText(value: replacement) }; return ErmaoShared.MetadataProviderUpdate(enabled: value.provider.enabled, priority: Int32(value.provider.priority), config: values, clearSecrets: Array(value.clearedSecretKeys)) }
    nonisolated func map(_ value: ErmaoShared.MetadataPipeline) -> MetadataPipeline { MetadataPipeline(mediaKind: map(value.mediaKind), providerIDs: value.providers.sorted { $0.position < $1.position }.map(\.providerId), enabledProviderIDs: Set(value.providers.filter(\.enabled).map(\.providerId))) }

    nonisolated func map(_ value: ErmaoShared.OpdsSettings) -> OPDSConfiguration { OPDSConfiguration(enabled: value.enabled, publicBaseURL: value.publicBaseUrl ?? "", catalogURL: value.catalogUrl, running: value.enabled && value.configured) }
    nonisolated func map(_ value: ErmaoShared.BackupArchive) -> BackupRecord { BackupRecord(id: value.id, filename: value.fileName ?? value.name, kind: value.kind ?? "manual", sizeBytes: value.sizeBytes, createdAt: date(value.createdAt) ?? .distantPast, bookCount: value.counts["books"]?.intValue ?? 0, progressCount: value.counts["readingProgresses"]?.intValue ?? 0, libraryCount: value.counts["libraries"]?.intValue ?? 0) }
    nonisolated func map(_ value: ErmaoShared.WorkDetailTab) -> AdministrativeWorkDetailSection { switch value.name { case "Ebook": .ebook; case "Comic": .comic; case "Audiobook": .audiobook; default: .chaptersAndContent } }
    nonisolated func map(_ value: AdministrativeWorkDetailSection) -> ErmaoShared.WorkDetailTab { switch value { case .ebook: .ebook; case .comic: .comic; case .audiobook: .audiobook; case .chaptersAndContent: .structure } }
    nonisolated func map(_ value: ErmaoShared.HealthRun) -> SystemHealthSnapshot { let epoch = value.finishedAt?.int64Value ?? value.startedAt; return SystemHealthSnapshot(checkedAt: Date(timeIntervalSince1970: Double(epoch) / 1000), components: value.items.map { HealthComponent(id: $0.id, name: $0.labelCode, group: $0.group, status: map($0.status), detail: $0.messageCode) }, queueRestartInProgress: false, queueRestartStatus: nil) }
    nonisolated func map(_ value: ErmaoShared.HealthCheckStatus) -> HealthStatus { switch value.name { case "Ok": .healthy; case "Warning": .warning; case "Error": .failed; default: .checking } }
    nonisolated func managementFilter(_ value: LogFilter, pageSize: Int32) -> ErmaoShared.ManagementEventFilter { ErmaoShared.ManagementEventFilter(page: 1, pageSize: pageSize, level: value.levels.count == 1 ? value.levels.first.map { levelWire($0) } : nil, source: value.source, targetType: nil, search: value.query.isEmpty ? nil : value.query, dateFrom: value.since.map { ISO8601DateFormatter().string(from: $0) }, dateTo: nil) }
    nonisolated func levelWire(_ value: LogLevel) -> String { switch value { case .information: "info"; case .warning: "warning"; case .error: "error" } }
    nonisolated func map(_ value: ErmaoShared.ManagementEventPage) -> LogPage { LogPage(events: value.events.map { ManagementLogEvent(id: $0.id, timestamp: date($0.createdAt) ?? .distantPast, level: $0.level.lowercased() == "error" ? .error : $0.level.lowercased() == "warning" ? .warning : .information, source: $0.source, summary: $0.message, correlationID: $0.metadata["correlationId"], target: $0.targetId) }, usedBytes: value.storage.sizeBytes, limitBytes: value.storage.maximumBytes) }
    nonisolated func csvField(_ value: String) -> String { "\"" + value.replacingOccurrences(of: "\"", with: "\"\"") + "\"" }
}
