// Generated by packages/reader-contracts/generate-reader-settings.py. Do not edit.
import type { ReaderReadingProgression, ReaderWritingMode } from './types';

export const READER_SCROLL_VIEWPORT_FRACTION = 0.88 as const;
export const READER_SCROLL_BOUNDARY_EPSILON_CSS_PIXELS = 1.0 as const;

export type ReaderPageTurnDirection = 'previous' | 'next';
export type ReaderPhysicalHorizontalSide = 'left' | 'right';

export function readerScrollAxis(writingMode: ReaderWritingMode) {
  return writingMode === 'vertical' ? 'horizontal' : 'vertical';
}

export function readerPhysicalHorizontalPageTurn(
  side: ReaderPhysicalHorizontalSide,
  readingProgression: ReaderReadingProgression
): ReaderPageTurnDirection {
  if (readingProgression === 'rtl') return side === 'left' ? 'next' : 'previous';
  return side === 'left' ? 'previous' : 'next';
}

export function readerAdjacentResourceProgression(direction: ReaderPageTurnDirection): 0 | 1 {
  return direction === 'previous' ? 1 : 0;
}
