// Generated by packages/reader-contracts/generate-reader-safety-policy.py. Do not edit.
export const READER_SAFETY_POLICY_SCHEMA_VERSION = 1 as const;
export const READER_SAFETY_POLICY_VERSION = 2 as const;
export const READER_SAFETY_POLICY_ID = "shuku.reader-safety" as const;
export const READER_SAFETY_POLICY_DIGEST = "d23214da7b731136eb4ce6a69a295f4a7ed8a7280cee444a6325caa77825ade2" as const;

export const READER_SAFETY_ACTIONS = [
  "ALLOW",
  "BLOCK_RESOURCE",
  "REJECT_PUBLICATION",
  "SANITIZE"
] as const;
export type ReaderSafetyAction = typeof READER_SAFETY_ACTIONS[number];
export const READER_SAFETY_ALGORITHM_IDS = [
  "ARCHIVE_STRUCTURE",
  "AUDIO_CONTAINER_MIME",
  "AUDIO_ENGINE_CODEC",
  "AUDIO_METADATA_BUDGET",
  "AUDIO_REDIRECT_POLICY",
  "AUDIO_TRACK_CHAPTER_BOUNDS",
  "BLOCK_MISSING_OPTIONAL_RESOURCE",
  "BOUNDED_TXT_CHUNK",
  "COMIC_ARCHIVE_BUDGET",
  "COMIC_ARCHIVE_STRUCTURE",
  "COMIC_MANIFEST_REVISION",
  "COMIC_PAGE_FAILURE",
  "COMIC_PAGE_MIME",
  "DOCTYPE_ALLOWLIST",
  "DRM_REJECTION",
  "EXACT_FORMAT_MIME",
  "MAX_ARCHIVE_ENTRIES",
  "MAX_ARCHIVE_ENTRY_BYTES",
  "MAX_ARCHIVE_EXPANDED_BYTES",
  "MAX_BINARY_RESOURCE_BYTES",
  "MAX_COMIC_MANIFEST_BYTES",
  "MAX_COMIC_PAGE_BYTES",
  "MAX_COMIC_PAGE_COUNT",
  "MAX_COMPRESSION_RATIO",
  "MAX_FB2_IMAGE_BYTES",
  "MAX_FB2_STRUCTURE",
  "MAX_MARKUP_BYTES",
  "MAX_ORIGINAL_BYTES",
  "MAX_TXT_MEMORY",
  "MAX_XML_BYTES",
  "PDF_ACTIVE_CONTENT",
  "PDF_PAGE_GEOMETRY",
  "PDF_RANGE_PROTOCOL",
  "PDF_RENDER_BUDGET",
  "REJECT_XML_ENTITY",
  "REQUIRE_READING_ORDER_MARKUP",
  "SANITIZE_CSS",
  "SANITIZE_MARKUP",
  "SANITIZE_SVG",
  "SANITIZE_URI"
] as const;
export type ReaderSafetyAlgorithmId = typeof READER_SAFETY_ALGORITHM_IDS[number];
export const READER_SAFETY_ERROR_CODES = [
  "AUDIO_DURATION_INVALID",
  "AUDIO_METADATA_LIMIT",
  "AUDIO_MIME_MISMATCH",
  "AUDIO_SECURITY_REJECTED",
  "COMIC_MIME_MISMATCH",
  "COMIC_PAGE_BLOCKED",
  "COMIC_RESOURCE_CHANGED",
  "COMIC_SECURITY_REJECTED",
  "ENGINE_CODEC_UNSUPPORTED",
  "ENGINE_POLICY_ALGORITHM_UNSUPPORTED",
  "PDF_PAGE_LIMIT",
  "PDF_RANGE_INVALID",
  "PDF_RENDER_LIMIT",
  "PLATFORM_POLICY_ALGORITHM_UNSUPPORTED",
  "PUBLICATION_CORRUPT",
  "PUBLICATION_DRM_UNSUPPORTED",
  "PUBLICATION_MIME_MISMATCH",
  "PUBLICATION_PARSER_LIMIT",
  "PUBLICATION_RESOURCE_BLOCKED",
  "PUBLICATION_SECURITY_REJECTED",
  "PUBLICATION_TOO_LARGE"
] as const;
export type ReaderSafetyErrorCode = typeof READER_SAFETY_ERROR_CODES[number];
export const READER_SAFETY_IMPLEMENTATION_FAILURE_CODES = [
  "ENGINE_POLICY_ALGORITHM_UNSUPPORTED",
  "PLATFORM_POLICY_ALGORITHM_UNSUPPORTED"
] as const;
export type ReaderSafetyImplementationFailureCode = typeof READER_SAFETY_IMPLEMENTATION_FAILURE_CODES[number];
export type ReaderSafetyConsumer = 'BACKEND' | 'WEB' | 'ANDROID' | 'IOS';
export type ReaderSafetyStage = 'ADMISSION' | 'PARSE' | 'SANITIZE' | 'RESOURCE' | 'RENDER' | 'DELIVERY' | 'PLAYBACK';
export type ReaderSafetyMorphology = 'REFLOWABLE' | 'PDF' | 'COMIC' | 'AUDIO';
export type ReaderSafetyDeliveryMode = 'DOWNLOAD_ORIGINAL' | 'STREAM' | 'PLAYER';
export type ReaderSafetyFormatLifecycle = 'ACTIVE' | 'RECEIVE_ONLY';

export const READER_SAFETY_FORMATS = {
  "EPUB": {
    "id": "EPUB",
    "morphology": "REFLOWABLE",
    "deliveryMode": "DOWNLOAD_ORIGINAL",
    "lifecycle": "ACTIVE",
    "extension": ".epub",
    "canonicalMimeType": "application/epub+zip",
    "acceptedMimeTypes": [
      "application/epub+zip"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "FB2": {
    "id": "FB2",
    "morphology": "REFLOWABLE",
    "deliveryMode": "DOWNLOAD_ORIGINAL",
    "lifecycle": "ACTIVE",
    "extension": ".fb2",
    "canonicalMimeType": "application/x-fictionbook+xml",
    "acceptedMimeTypes": [
      "application/x-fictionbook+xml",
      "text/xml",
      "application/xml"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "TXT": {
    "id": "TXT",
    "morphology": "REFLOWABLE",
    "deliveryMode": "DOWNLOAD_ORIGINAL",
    "lifecycle": "ACTIVE",
    "extension": ".txt",
    "canonicalMimeType": "text/plain",
    "acceptedMimeTypes": [
      "text/plain"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "MOBI": {
    "id": "MOBI",
    "morphology": "REFLOWABLE",
    "deliveryMode": "DOWNLOAD_ORIGINAL",
    "lifecycle": "ACTIVE",
    "extension": ".mobi",
    "canonicalMimeType": "application/x-mobipocket-ebook",
    "acceptedMimeTypes": [
      "application/x-mobipocket-ebook"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "AZW": {
    "id": "AZW",
    "morphology": "REFLOWABLE",
    "deliveryMode": "DOWNLOAD_ORIGINAL",
    "lifecycle": "ACTIVE",
    "extension": ".azw",
    "canonicalMimeType": "application/vnd.amazon.ebook",
    "acceptedMimeTypes": [
      "application/vnd.amazon.ebook"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "AZW3": {
    "id": "AZW3",
    "morphology": "REFLOWABLE",
    "deliveryMode": "DOWNLOAD_ORIGINAL",
    "lifecycle": "ACTIVE",
    "extension": ".azw3",
    "canonicalMimeType": "application/vnd.amazon.ebook",
    "acceptedMimeTypes": [
      "application/vnd.amazon.ebook",
      "application/x-mobipocket-ebook"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "PRC": {
    "id": "PRC",
    "morphology": "REFLOWABLE",
    "deliveryMode": "DOWNLOAD_ORIGINAL",
    "lifecycle": "ACTIVE",
    "extension": ".prc",
    "canonicalMimeType": "application/x-mobipocket-ebook",
    "acceptedMimeTypes": [
      "application/x-mobipocket-ebook"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "PDF": {
    "id": "PDF",
    "morphology": "PDF",
    "deliveryMode": "STREAM",
    "lifecycle": "ACTIVE",
    "extension": ".pdf",
    "canonicalMimeType": "application/pdf",
    "acceptedMimeTypes": [
      "application/pdf"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "CBZ": {
    "id": "CBZ",
    "morphology": "COMIC",
    "deliveryMode": "STREAM",
    "lifecycle": "ACTIVE",
    "extension": ".cbz",
    "canonicalMimeType": "application/vnd.comicbook+zip",
    "acceptedMimeTypes": [
      "application/vnd.comicbook+zip",
      "application/x-cbz"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "ZIP": {
    "id": "ZIP",
    "morphology": "COMIC",
    "deliveryMode": "STREAM",
    "lifecycle": "ACTIVE",
    "extension": ".zip",
    "canonicalMimeType": "application/zip",
    "acceptedMimeTypes": [
      "application/zip"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "CBR": {
    "id": "CBR",
    "morphology": "COMIC",
    "deliveryMode": "STREAM",
    "lifecycle": "ACTIVE",
    "extension": ".cbr",
    "canonicalMimeType": "application/vnd.comicbook-rar",
    "acceptedMimeTypes": [
      "application/vnd.comicbook-rar",
      "application/x-cbr"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "RAR": {
    "id": "RAR",
    "morphology": "COMIC",
    "deliveryMode": "STREAM",
    "lifecycle": "ACTIVE",
    "extension": ".rar",
    "canonicalMimeType": "application/vnd.rar",
    "acceptedMimeTypes": [
      "application/vnd.rar",
      "application/x-rar-compressed"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "IMAGE_DIR": {
    "id": "IMAGE_DIR",
    "morphology": "COMIC",
    "deliveryMode": "STREAM",
    "lifecycle": "ACTIVE",
    "extension": null,
    "canonicalMimeType": null,
    "acceptedMimeTypes": [],
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "AUDIO": {
    "id": "AUDIO",
    "morphology": "AUDIO",
    "deliveryMode": "PLAYER",
    "lifecycle": "ACTIVE",
    "extension": null,
    "canonicalMimeType": null,
    "acceptedMimeTypes": [],
    "requiredConsumers": [
      "BACKEND",
      "WEB"
    ]
  },
  "AUDIOBOOK_DIR": {
    "id": "AUDIOBOOK_DIR",
    "morphology": "AUDIO",
    "deliveryMode": "PLAYER",
    "lifecycle": "ACTIVE",
    "extension": null,
    "canonicalMimeType": null,
    "acceptedMimeTypes": [],
    "requiredConsumers": [
      "BACKEND",
      "WEB"
    ]
  },
  "AUDIOBOOK": {
    "id": "AUDIOBOOK",
    "morphology": "AUDIO",
    "deliveryMode": "PLAYER",
    "lifecycle": "RECEIVE_ONLY",
    "extension": null,
    "canonicalMimeType": null,
    "acceptedMimeTypes": [],
    "requiredConsumers": [
      "BACKEND",
      "WEB"
    ]
  },
  "M4B": {
    "id": "M4B",
    "morphology": "AUDIO",
    "deliveryMode": "PLAYER",
    "lifecycle": "RECEIVE_ONLY",
    "extension": ".m4b",
    "canonicalMimeType": "audio/mp4",
    "acceptedMimeTypes": [
      "audio/mp4"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB"
    ]
  },
  "M4A": {
    "id": "M4A",
    "morphology": "AUDIO",
    "deliveryMode": "PLAYER",
    "lifecycle": "RECEIVE_ONLY",
    "extension": ".m4a",
    "canonicalMimeType": "audio/mp4",
    "acceptedMimeTypes": [
      "audio/mp4"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB"
    ]
  },
  "MP3": {
    "id": "MP3",
    "morphology": "AUDIO",
    "deliveryMode": "PLAYER",
    "lifecycle": "RECEIVE_ONLY",
    "extension": ".mp3",
    "canonicalMimeType": "audio/mpeg",
    "acceptedMimeTypes": [
      "audio/mpeg"
    ],
    "requiredConsumers": [
      "BACKEND",
      "WEB"
    ]
  }
} as const;
export type ReaderSafetyFormat = keyof typeof READER_SAFETY_FORMATS;
export type ReaderSafetyFormatDefinition = typeof READER_SAFETY_FORMATS[ReaderSafetyFormat];

export const READER_SAFETY_BUDGETS = {
  "originalMaxBytes": 2147483648,
  "binaryResourceMaxBytes": 268435456,
  "archiveEntryMaxCount": 10000,
  "archiveExpandedMaxBytes": 2147483648,
  "archiveEntryMaxBytes": 268435456,
  "archiveCompressionRatioMax": 200,
  "xmlControlDocumentMaxBytes": 16777216,
  "reflowableMarkupMaxBytes": 67108864,
  "fb2TextMaxBytes": 67108864,
  "fb2MaxDepth": 128,
  "fb2MaxNodes": 500000,
  "fb2TextMaxCharacters": 67108864,
  "fb2EncodedImageMaxBytes": 29360128,
  "fb2DecodedImageMaxBytes": 20971520,
  "fb2DecodedImagesTotalMaxBytes": 134217728,
  "txtMemoryMaxBytes": 67108864,
  "txtChunkMaxCharacters": 65536,
  "pdfPageMaxCount": 20000,
  "pdfRenderMaxPixels": 12000000,
  "pdfCanvasMaxDimension": 4096,
  "pdfRangeChunkBytes": 262144,
  "pdfRangeRequestMaxBytes": 1048576,
  "pdfRangeMaxConcurrent": 2,
  "pdfRangeMemoryCacheMaxBytes": 8388608,
  "comicPageMaxCount": 10000,
  "comicPageMaxBytes": 33554432,
  "comicManifestMaxBytes": 2097152,
  "comicExpandedMaxBytes": 2147483648,
  "comicCompressionRatioMax": 200,
  "audioTrackMaxCount": 10000,
  "audioChapterMaxCount": 10000,
  "audioMetadataMaxBytes": 1048576,
  "audioArtworkMaxBytes": 20971520
} as const;
export type ReaderSafetyBudgetName = keyof typeof READER_SAFETY_BUDGETS;
export const READER_SAFETY_PROFILES = {
  "reflowable": {
    "safeDoctypes": [
      {
        "name": "html",
        "publicId": "-//W3C//DTD XHTML 1.0 Strict//EN",
        "systemId": "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"
      },
      {
        "name": "html",
        "publicId": "-//W3C//DTD XHTML 1.0 Transitional//EN",
        "systemId": "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"
      },
      {
        "name": "html",
        "publicId": "-//W3C//DTD XHTML 1.0 Frameset//EN",
        "systemId": "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd"
      },
      {
        "name": "html",
        "publicId": "-//W3C//DTD XHTML 1.1//EN",
        "systemId": "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"
      },
      {
        "name": "html",
        "publicId": "-//W3C//DTD XHTML 1.0 Strict//EN",
        "systemId": "https://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"
      },
      {
        "name": "html",
        "publicId": "-//W3C//DTD XHTML 1.0 Transitional//EN",
        "systemId": "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"
      },
      {
        "name": "html",
        "publicId": "-//W3C//DTD XHTML 1.0 Frameset//EN",
        "systemId": "https://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd"
      },
      {
        "name": "html",
        "publicId": "-//W3C//DTD XHTML 1.1//EN",
        "systemId": "https://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"
      }
    ],
    "externalDtdResolution": false,
    "rejectInternalSubset": true,
    "rejectCustomEntities": true,
    "namedEntityCodepoints": {
      "AElig": 198,
      "Aacute": 193,
      "Acirc": 194,
      "Agrave": 192,
      "Alpha": 913,
      "Aring": 197,
      "Atilde": 195,
      "Auml": 196,
      "Beta": 914,
      "Ccedil": 199,
      "Chi": 935,
      "Dagger": 8225,
      "Delta": 916,
      "ETH": 208,
      "Eacute": 201,
      "Ecirc": 202,
      "Egrave": 200,
      "Epsilon": 917,
      "Eta": 919,
      "Euml": 203,
      "Gamma": 915,
      "Iacute": 205,
      "Icirc": 206,
      "Igrave": 204,
      "Iota": 921,
      "Iuml": 207,
      "Kappa": 922,
      "Lambda": 923,
      "Mu": 924,
      "Ntilde": 209,
      "Nu": 925,
      "OElig": 338,
      "Oacute": 211,
      "Ocirc": 212,
      "Ograve": 210,
      "Omega": 937,
      "Omicron": 927,
      "Oslash": 216,
      "Otilde": 213,
      "Ouml": 214,
      "Phi": 934,
      "Pi": 928,
      "Prime": 8243,
      "Psi": 936,
      "Rho": 929,
      "Scaron": 352,
      "Sigma": 931,
      "THORN": 222,
      "Tau": 932,
      "Theta": 920,
      "Uacute": 218,
      "Ucirc": 219,
      "Ugrave": 217,
      "Upsilon": 933,
      "Uuml": 220,
      "Xi": 926,
      "Yacute": 221,
      "Yuml": 376,
      "Zeta": 918,
      "aacute": 225,
      "acirc": 226,
      "acute": 180,
      "aelig": 230,
      "agrave": 224,
      "alefsym": 8501,
      "alpha": 945,
      "amp": 38,
      "and": 8743,
      "ang": 8736,
      "apos": 39,
      "aring": 229,
      "asymp": 8776,
      "atilde": 227,
      "auml": 228,
      "bdquo": 8222,
      "beta": 946,
      "brvbar": 166,
      "bull": 8226,
      "cap": 8745,
      "ccedil": 231,
      "cedil": 184,
      "cent": 162,
      "chi": 967,
      "circ": 710,
      "clubs": 9827,
      "cong": 8773,
      "copy": 169,
      "crarr": 8629,
      "cup": 8746,
      "curren": 164,
      "dArr": 8659,
      "dagger": 8224,
      "darr": 8595,
      "deg": 176,
      "delta": 948,
      "diams": 9830,
      "divide": 247,
      "eacute": 233,
      "ecirc": 234,
      "egrave": 232,
      "empty": 8709,
      "emsp": 8195,
      "ensp": 8194,
      "epsilon": 949,
      "equiv": 8801,
      "eta": 951,
      "eth": 240,
      "euml": 235,
      "euro": 8364,
      "exist": 8707,
      "fnof": 402,
      "forall": 8704,
      "frac12": 189,
      "frac14": 188,
      "frac34": 190,
      "frasl": 8260,
      "gamma": 947,
      "ge": 8805,
      "gt": 62,
      "hArr": 8660,
      "harr": 8596,
      "hearts": 9829,
      "hellip": 8230,
      "iacute": 237,
      "icirc": 238,
      "iexcl": 161,
      "igrave": 236,
      "image": 8465,
      "infin": 8734,
      "int": 8747,
      "iota": 953,
      "iquest": 191,
      "isin": 8712,
      "iuml": 239,
      "kappa": 954,
      "lArr": 8656,
      "lambda": 955,
      "lang": 9001,
      "laquo": 171,
      "larr": 8592,
      "lceil": 8968,
      "ldquo": 8220,
      "le": 8804,
      "lfloor": 8970,
      "lowast": 8727,
      "loz": 9674,
      "lrm": 8206,
      "lsaquo": 8249,
      "lsquo": 8216,
      "lt": 60,
      "macr": 175,
      "mdash": 8212,
      "micro": 181,
      "middot": 183,
      "minus": 8722,
      "mu": 956,
      "nabla": 8711,
      "nbsp": 160,
      "ndash": 8211,
      "ne": 8800,
      "ni": 8715,
      "not": 172,
      "notin": 8713,
      "nsub": 8836,
      "ntilde": 241,
      "nu": 957,
      "oacute": 243,
      "ocirc": 244,
      "oelig": 339,
      "ograve": 242,
      "oline": 8254,
      "omega": 969,
      "omicron": 959,
      "oplus": 8853,
      "or": 8744,
      "ordf": 170,
      "ordm": 186,
      "oslash": 248,
      "otilde": 245,
      "otimes": 8855,
      "ouml": 246,
      "para": 182,
      "part": 8706,
      "permil": 8240,
      "perp": 8869,
      "phi": 966,
      "pi": 960,
      "piv": 982,
      "plusmn": 177,
      "pound": 163,
      "prime": 8242,
      "prod": 8719,
      "prop": 8733,
      "psi": 968,
      "quot": 34,
      "rArr": 8658,
      "radic": 8730,
      "rang": 9002,
      "raquo": 187,
      "rarr": 8594,
      "rceil": 8969,
      "rdquo": 8221,
      "real": 8476,
      "reg": 174,
      "rfloor": 8971,
      "rho": 961,
      "rlm": 8207,
      "rsaquo": 8250,
      "rsquo": 8217,
      "sbquo": 8218,
      "scaron": 353,
      "sdot": 8901,
      "sect": 167,
      "shy": 173,
      "sigma": 963,
      "sigmaf": 962,
      "sim": 8764,
      "spades": 9824,
      "sub": 8834,
      "sube": 8838,
      "sum": 8721,
      "sup": 8835,
      "sup1": 185,
      "sup2": 178,
      "sup3": 179,
      "supe": 8839,
      "szlig": 223,
      "tau": 964,
      "there4": 8756,
      "theta": 952,
      "thetasym": 977,
      "thinsp": 8201,
      "thorn": 254,
      "tilde": 732,
      "times": 215,
      "trade": 8482,
      "uArr": 8657,
      "uacute": 250,
      "uarr": 8593,
      "ucirc": 251,
      "ugrave": 249,
      "uml": 168,
      "upsih": 978,
      "upsilon": 965,
      "uuml": 252,
      "weierp": 8472,
      "xi": 958,
      "yacute": 253,
      "yen": 165,
      "yuml": 255,
      "zeta": 950,
      "zwj": 8205,
      "zwnj": 8204
    },
    "readingOrderMarkupMimeTypes": [
      "application/xhtml+xml",
      "text/html"
    ],
    "embeddedImageExtensionsByMimeType": {
      "image/jpeg": ".jpg",
      "image/png": ".png",
      "image/gif": ".gif",
      "image/webp": ".webp"
    },
    "sanitizedElements": [
      "script",
      "iframe",
      "object",
      "embed",
      "form",
      "base"
    ],
    "sanitizedAttributes": [
      "srcdoc"
    ],
    "sanitizedAttributePrefixes": [
      "on"
    ],
    "sanitizedMetaHttpEquivValues": [
      "refresh",
      "content-security-policy"
    ],
    "blockedAuthorSchemes": [
      "javascript",
      "file",
      "data",
      "blob"
    ],
    "remoteSubresourceSchemes": [
      "http",
      "https"
    ],
    "userNavigationSchemes": [
      "http",
      "https",
      "mailto",
      "tel"
    ],
    "trustedRuntimeSchemes": [
      "blob",
      "data"
    ],
    "uriAttributePolicies": [
      {
        "elements": [
          "*"
        ],
        "attribute": "src",
        "syntax": "SCALAR",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "*"
        ],
        "attribute": "srcset",
        "syntax": "SRCSET",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "*"
        ],
        "attribute": "style",
        "syntax": "CSS",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "*"
        ],
        "attribute": "xml:base",
        "syntax": "SCALAR",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "link"
        ],
        "attribute": "href",
        "syntax": "SCALAR",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "video"
        ],
        "attribute": "poster",
        "syntax": "SCALAR",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "*"
        ],
        "attribute": "background",
        "syntax": "SCALAR",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "html"
        ],
        "attribute": "manifest",
        "syntax": "SCALAR",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "img",
          "input"
        ],
        "attribute": "usemap",
        "syntax": "SCALAR",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "object"
        ],
        "attribute": "data",
        "syntax": "SCALAR",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "object",
          "applet"
        ],
        "attribute": "codebase",
        "syntax": "SCALAR",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "applet"
        ],
        "attribute": "code",
        "syntax": "SCALAR",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "applet"
        ],
        "attribute": "archive",
        "syntax": "SPACE_SEPARATED",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "image",
          "use",
          "feimage"
        ],
        "attribute": "href",
        "syntax": "SCALAR",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "image",
          "use",
          "feimage"
        ],
        "attribute": "xlink:href",
        "syntax": "SCALAR",
        "purpose": "SUBRESOURCE"
      },
      {
        "elements": [
          "a",
          "area"
        ],
        "attribute": "href",
        "syntax": "SCALAR",
        "purpose": "USER_NAVIGATION"
      },
      {
        "elements": [
          "a"
        ],
        "attribute": "xlink:href",
        "syntax": "SCALAR",
        "purpose": "USER_NAVIGATION"
      },
      {
        "elements": [
          "blockquote",
          "q",
          "ins",
          "del"
        ],
        "attribute": "cite",
        "syntax": "SCALAR",
        "purpose": "USER_NAVIGATION"
      },
      {
        "elements": [
          "a",
          "area"
        ],
        "attribute": "ping",
        "syntax": "SPACE_SEPARATED",
        "purpose": "ALWAYS_REMOVE"
      },
      {
        "elements": [
          "form"
        ],
        "attribute": "action",
        "syntax": "SCALAR",
        "purpose": "ALWAYS_REMOVE"
      },
      {
        "elements": [
          "button",
          "input"
        ],
        "attribute": "formaction",
        "syntax": "SCALAR",
        "purpose": "ALWAYS_REMOVE"
      }
    ],
    "allowedFontObfuscationAlgorithms": [
      "http://www.idpf.org/2008/embedding",
      "http://ns.adobe.com/pdf/enc#RC"
    ],
    "svgSanitizedElements": [
      "script",
      "foreignObject",
      "iframe",
      "object",
      "embed"
    ],
    "cssTextElements": [
      "style"
    ],
    "cssSanitizedConstructs": [
      "REMOTE_IMPORT",
      "REMOTE_URL",
      "EXPRESSION",
      "BEHAVIOR",
      "MOZ_BINDING"
    ],
    "archiveFatalFindings": [
      "PATH_ESCAPE",
      "ABSOLUTE_PATH",
      "BACKSLASH_PATH",
      "NUL_PATH",
      "DOT_SEGMENT",
      "DUPLICATE_CANONICAL_ENTRY",
      "SYMLINK",
      "ENCRYPTED_ENTRY",
      "OVERLAPPING_ENTRY",
      "CRC_MISMATCH"
    ]
  },
  "pdf": {
    "blockedActions": [
      "JAVASCRIPT",
      "XFA",
      "FORM_ACTION",
      "LAUNCH",
      "EXTERNAL_DOCUMENT",
      "DOCUMENT_NETWORK"
    ],
    "requireFinitePageGeometry": true,
    "requireIdentityContentEncoding": true,
    "requireStrongRevision": true,
    "engineRequestLimit": "SOURCE_LENGTH",
    "largeRequestAction": "MATERIALIZE_VERIFIED_ORIGINAL",
    "allowWholeResponseFallback": false
  },
  "comic": {
    "allowedPageMimeTypes": [
      "image/jpeg",
      "image/png",
      "image/gif",
      "image/webp"
    ],
    "pageMimeTypesByExtension": {
      ".jpg": "image/jpeg",
      ".jpeg": "image/jpeg",
      ".png": "image/png",
      ".gif": "image/gif",
      ".webp": "image/webp"
    },
    "archiveFatalFindings": [
      "PATH_ESCAPE",
      "ABSOLUTE_PATH",
      "BACKSLASH_PATH",
      "NUL_PATH",
      "DOT_SEGMENT",
      "DUPLICATE_CANONICAL_ENTRY",
      "SYMLINK",
      "HARDLINK",
      "ENCRYPTED_ENTRY",
      "OVERLAPPING_ENTRY",
      "CRC_MISMATCH"
    ],
    "singlePageDecodeFailureAction": "BLOCK_RESOURCE",
    "manifestRevisionRequired": true
  },
  "audio": {
    "containerMimeTypes": {
      ".aac": "audio/aac",
      ".ac3": "audio/ac3",
      ".adx": "audio/x-adx",
      ".aif": "audio/aiff",
      ".aifc": "audio/aiff",
      ".aiff": "audio/aiff",
      ".amr": "audio/amr",
      ".ape": "audio/x-ape",
      ".aptx": "audio/x-aptx",
      ".aptxhd": "audio/x-aptxhd",
      ".au": "audio/basic",
      ".caf": "audio/x-caf",
      ".dff": "audio/x-dff",
      ".dsf": "audio/x-dsf",
      ".dts": "audio/vnd.dts",
      ".eac3": "audio/eac3",
      ".flac": "audio/flac",
      ".g722": "audio/x-g722",
      ".g726": "audio/x-g726",
      ".gsm": "audio/x-gsm",
      ".lbc": "audio/x-lbc",
      ".m4a": "audio/mp4",
      ".m4b": "audio/mp4",
      ".m4r": "audio/mp4",
      ".mka": "audio/x-matroska",
      ".mlp": "audio/x-mlp",
      ".mp2": "audio/mpeg",
      ".mp3": "audio/mpeg",
      ".mpc": "audio/x-mpc",
      ".oga": "audio/ogg",
      ".ogg": "audio/ogg",
      ".oma": "audio/x-oma",
      ".opus": "audio/ogg",
      ".qcp": "audio/x-qcp",
      ".ra": "audio/vnd.rn-realaudio",
      ".rf64": "audio/wav",
      ".shn": "audio/x-shn",
      ".snd": "audio/basic",
      ".sph": "audio/x-sph",
      ".spx": "audio/ogg",
      ".tak": "audio/x-tak",
      ".thd": "audio/x-thd",
      ".tta": "audio/x-tta",
      ".voc": "audio/x-voc",
      ".w64": "audio/wav",
      ".wav": "audio/wav",
      ".wave": "audio/wav",
      ".weba": "audio/webm",
      ".wma": "audio/x-ms-wma",
      ".wv": "audio/x-wv",
      ".xma": "audio/x-xma"
    },
    "codecDecision": "ENGINE_CAPABILITY",
    "blockedRedirectSchemes": [
      "file",
      "data",
      "blob",
      "javascript"
    ],
    "requireFiniteNonNegativeDuration": true,
    "requireOrderedTrackIdentity": true
  }
} as const;

export const READER_SAFETY_RULE_IDS = {
  "COMMON_EXACT_FORMAT_MIME": "COMMON.EXACT_FORMAT_MIME",
  "COMMON_ORIGINAL_MAX_BYTES": "COMMON.ORIGINAL_MAX_BYTES",
  "COMMON_BINARY_RESOURCE_MAX_BYTES": "COMMON.BINARY_RESOURCE_MAX_BYTES",
  "COMMON_DRM_REJECTED": "COMMON.DRM_REJECTED",
  "REFLOWABLE_SAFE_STANDARD_DOCTYPE": "REFLOWABLE.SAFE_STANDARD_DOCTYPE",
  "REFLOWABLE_REJECT_XML_ENTITY": "REFLOWABLE.REJECT_XML_ENTITY",
  "REFLOWABLE_SANITIZE_MARKUP": "REFLOWABLE.SANITIZE_MARKUP",
  "REFLOWABLE_SANITIZE_URI": "REFLOWABLE.SANITIZE_URI",
  "REFLOWABLE_SANITIZE_SVG": "REFLOWABLE.SANITIZE_SVG",
  "REFLOWABLE_SANITIZE_CSS": "REFLOWABLE.SANITIZE_CSS",
  "REFLOWABLE_OPTIONAL_RESOURCE_FAILURE": "REFLOWABLE.OPTIONAL_RESOURCE_FAILURE",
  "REFLOWABLE_REQUIRED_READING_ORDER_MARKUP": "REFLOWABLE.REQUIRED_READING_ORDER_MARKUP",
  "REFLOWABLE_XML_CONTROL_DOCUMENT_MAX_BYTES": "REFLOWABLE.XML_CONTROL_DOCUMENT_MAX_BYTES",
  "REFLOWABLE_MARKUP_MAX_BYTES": "REFLOWABLE.MARKUP_MAX_BYTES",
  "EPUB_ARCHIVE_STRUCTURE": "EPUB.ARCHIVE_STRUCTURE",
  "EPUB_ARCHIVE_ENTRY_MAX_COUNT": "EPUB.ARCHIVE_ENTRY_MAX_COUNT",
  "EPUB_ARCHIVE_EXPANDED_MAX_BYTES": "EPUB.ARCHIVE_EXPANDED_MAX_BYTES",
  "EPUB_ARCHIVE_ENTRY_MAX_BYTES": "EPUB.ARCHIVE_ENTRY_MAX_BYTES",
  "EPUB_ARCHIVE_COMPRESSION_RATIO": "EPUB.ARCHIVE_COMPRESSION_RATIO",
  "FB2_STRUCTURE_BUDGET": "FB2.STRUCTURE_BUDGET",
  "FB2_IMAGE_BUDGET": "FB2.IMAGE_BUDGET",
  "TXT_MEMORY_BUDGET": "TXT.MEMORY_BUDGET",
  "TXT_BOUNDED_CHUNK": "TXT.BOUNDED_CHUNK",
  "PDF_DISABLE_ACTIVE_CONTENT": "PDF.DISABLE_ACTIVE_CONTENT",
  "PDF_PAGE_GEOMETRY": "PDF.PAGE_GEOMETRY",
  "PDF_RENDER_BUDGET": "PDF.RENDER_BUDGET",
  "PDF_RANGE_PROTOCOL": "PDF.RANGE_PROTOCOL",
  "COMIC_PAGE_MIME": "COMIC.PAGE_MIME",
  "COMIC_ARCHIVE_STRUCTURE": "COMIC.ARCHIVE_STRUCTURE",
  "COMIC_PAGE_MAX_COUNT": "COMIC.PAGE_MAX_COUNT",
  "COMIC_ARCHIVE_BUDGET": "COMIC.ARCHIVE_BUDGET",
  "COMIC_PAGE_MAX_BYTES": "COMIC.PAGE_MAX_BYTES",
  "COMIC_MANIFEST_MAX_BYTES": "COMIC.MANIFEST_MAX_BYTES",
  "COMIC_PAGE_DECODE_FAILURE": "COMIC.PAGE_DECODE_FAILURE",
  "COMIC_MANIFEST_REVISION": "COMIC.MANIFEST_REVISION",
  "AUDIO_CONTAINER_MIME": "AUDIO.CONTAINER_MIME",
  "AUDIO_ORIGINAL_MAX_BYTES": "AUDIO.ORIGINAL_MAX_BYTES",
  "AUDIO_ENGINE_CODEC": "AUDIO.ENGINE_CODEC",
  "AUDIO_TRACK_AND_CHAPTER_BOUNDS": "AUDIO.TRACK_AND_CHAPTER_BOUNDS",
  "AUDIO_METADATA_BUDGET": "AUDIO.METADATA_BUDGET",
  "AUDIO_REDIRECT_POLICY": "AUDIO.REDIRECT_POLICY"
} as const;
export type ReaderSafetyRuleId = typeof READER_SAFETY_RULE_IDS[keyof typeof READER_SAFETY_RULE_IDS];
export const READER_SAFETY_RULES = {
  "COMMON.EXACT_FORMAT_MIME": {
    "id": "COMMON.EXACT_FORMAT_MIME",
    "formats": [
      "EPUB",
      "FB2",
      "TXT",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC",
      "PDF",
      "CBZ",
      "ZIP",
      "CBR",
      "RAR"
    ],
    "stage": "ADMISSION",
    "algorithm": "EXACT_FORMAT_MIME",
    "parameterRefs": [
      "formats"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_MIME_MISMATCH",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "COMMON.ORIGINAL_MAX_BYTES": {
    "id": "COMMON.ORIGINAL_MAX_BYTES",
    "formats": [
      "EPUB",
      "FB2",
      "TXT",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC",
      "PDF",
      "CBZ",
      "ZIP",
      "CBR",
      "RAR"
    ],
    "stage": "ADMISSION",
    "algorithm": "MAX_ORIGINAL_BYTES",
    "parameterRefs": [
      "budgets.originalMaxBytes"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_TOO_LARGE",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "COMMON.BINARY_RESOURCE_MAX_BYTES": {
    "id": "COMMON.BINARY_RESOURCE_MAX_BYTES",
    "formats": [
      "EPUB",
      "FB2",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC"
    ],
    "stage": "RESOURCE",
    "algorithm": "MAX_BINARY_RESOURCE_BYTES",
    "parameterRefs": [
      "budgets.binaryResourceMaxBytes"
    ],
    "action": "BLOCK_RESOURCE",
    "errorCode": "PUBLICATION_RESOURCE_BLOCKED",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "COMMON.DRM_REJECTED": {
    "id": "COMMON.DRM_REJECTED",
    "formats": [
      "EPUB",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC",
      "PDF"
    ],
    "stage": "PARSE",
    "algorithm": "DRM_REJECTION",
    "parameterRefs": [
      "profiles.reflowable.allowedFontObfuscationAlgorithms"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_DRM_UNSUPPORTED",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "REFLOWABLE.SAFE_STANDARD_DOCTYPE": {
    "id": "REFLOWABLE.SAFE_STANDARD_DOCTYPE",
    "formats": [
      "EPUB",
      "FB2"
    ],
    "stage": "PARSE",
    "algorithm": "DOCTYPE_ALLOWLIST",
    "parameterRefs": [
      "profiles.reflowable.safeDoctypes",
      "profiles.reflowable.externalDtdResolution"
    ],
    "action": "ALLOW",
    "errorCode": null,
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "REFLOWABLE.REJECT_XML_ENTITY": {
    "id": "REFLOWABLE.REJECT_XML_ENTITY",
    "formats": [
      "EPUB",
      "FB2"
    ],
    "stage": "PARSE",
    "algorithm": "REJECT_XML_ENTITY",
    "parameterRefs": [
      "profiles.reflowable.rejectInternalSubset",
      "profiles.reflowable.rejectCustomEntities",
      "profiles.reflowable.externalDtdResolution",
      "profiles.reflowable.namedEntityCodepoints"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_SECURITY_REJECTED",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "REFLOWABLE.SANITIZE_MARKUP": {
    "id": "REFLOWABLE.SANITIZE_MARKUP",
    "formats": [
      "EPUB",
      "FB2",
      "TXT",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC"
    ],
    "stage": "SANITIZE",
    "algorithm": "SANITIZE_MARKUP",
    "parameterRefs": [
      "profiles.reflowable.sanitizedElements",
      "profiles.reflowable.sanitizedAttributes",
      "profiles.reflowable.sanitizedAttributePrefixes",
      "profiles.reflowable.sanitizedMetaHttpEquivValues"
    ],
    "action": "SANITIZE",
    "errorCode": null,
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "REFLOWABLE.SANITIZE_URI": {
    "id": "REFLOWABLE.SANITIZE_URI",
    "formats": [
      "EPUB",
      "FB2",
      "TXT",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC"
    ],
    "stage": "SANITIZE",
    "algorithm": "SANITIZE_URI",
    "parameterRefs": [
      "profiles.reflowable.blockedAuthorSchemes",
      "profiles.reflowable.remoteSubresourceSchemes",
      "profiles.reflowable.userNavigationSchemes",
      "profiles.reflowable.trustedRuntimeSchemes",
      "profiles.reflowable.uriAttributePolicies"
    ],
    "action": "SANITIZE",
    "errorCode": null,
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "REFLOWABLE.SANITIZE_SVG": {
    "id": "REFLOWABLE.SANITIZE_SVG",
    "formats": [
      "EPUB",
      "FB2"
    ],
    "stage": "SANITIZE",
    "algorithm": "SANITIZE_SVG",
    "parameterRefs": [
      "profiles.reflowable.svgSanitizedElements",
      "profiles.reflowable.sanitizedAttributePrefixes",
      "profiles.reflowable.blockedAuthorSchemes",
      "profiles.reflowable.remoteSubresourceSchemes"
    ],
    "action": "SANITIZE",
    "errorCode": null,
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "REFLOWABLE.SANITIZE_CSS": {
    "id": "REFLOWABLE.SANITIZE_CSS",
    "formats": [
      "EPUB",
      "FB2",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC"
    ],
    "stage": "SANITIZE",
    "algorithm": "SANITIZE_CSS",
    "parameterRefs": [
      "profiles.reflowable.cssTextElements",
      "profiles.reflowable.cssSanitizedConstructs",
      "profiles.reflowable.remoteSubresourceSchemes",
      "profiles.reflowable.blockedAuthorSchemes"
    ],
    "action": "SANITIZE",
    "errorCode": null,
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "REFLOWABLE.OPTIONAL_RESOURCE_FAILURE": {
    "id": "REFLOWABLE.OPTIONAL_RESOURCE_FAILURE",
    "formats": [
      "EPUB",
      "FB2",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC"
    ],
    "stage": "RESOURCE",
    "algorithm": "BLOCK_MISSING_OPTIONAL_RESOURCE",
    "parameterRefs": [],
    "action": "BLOCK_RESOURCE",
    "errorCode": "PUBLICATION_RESOURCE_BLOCKED",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "REFLOWABLE.REQUIRED_READING_ORDER_MARKUP": {
    "id": "REFLOWABLE.REQUIRED_READING_ORDER_MARKUP",
    "formats": [
      "EPUB",
      "FB2",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC"
    ],
    "stage": "PARSE",
    "algorithm": "REQUIRE_READING_ORDER_MARKUP",
    "parameterRefs": [
      "profiles.reflowable.readingOrderMarkupMimeTypes"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_CORRUPT",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "REFLOWABLE.XML_CONTROL_DOCUMENT_MAX_BYTES": {
    "id": "REFLOWABLE.XML_CONTROL_DOCUMENT_MAX_BYTES",
    "formats": [
      "EPUB",
      "FB2"
    ],
    "stage": "PARSE",
    "algorithm": "MAX_XML_BYTES",
    "parameterRefs": [
      "budgets.xmlControlDocumentMaxBytes"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_PARSER_LIMIT",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "REFLOWABLE.MARKUP_MAX_BYTES": {
    "id": "REFLOWABLE.MARKUP_MAX_BYTES",
    "formats": [
      "EPUB",
      "FB2",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC"
    ],
    "stage": "PARSE",
    "algorithm": "MAX_MARKUP_BYTES",
    "parameterRefs": [
      "budgets.reflowableMarkupMaxBytes"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_PARSER_LIMIT",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "EPUB.ARCHIVE_STRUCTURE": {
    "id": "EPUB.ARCHIVE_STRUCTURE",
    "formats": [
      "EPUB"
    ],
    "stage": "PARSE",
    "algorithm": "ARCHIVE_STRUCTURE",
    "parameterRefs": [
      "profiles.reflowable.archiveFatalFindings"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_SECURITY_REJECTED",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "EPUB.ARCHIVE_ENTRY_MAX_COUNT": {
    "id": "EPUB.ARCHIVE_ENTRY_MAX_COUNT",
    "formats": [
      "EPUB"
    ],
    "stage": "PARSE",
    "algorithm": "MAX_ARCHIVE_ENTRIES",
    "parameterRefs": [
      "budgets.archiveEntryMaxCount"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_PARSER_LIMIT",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "EPUB.ARCHIVE_EXPANDED_MAX_BYTES": {
    "id": "EPUB.ARCHIVE_EXPANDED_MAX_BYTES",
    "formats": [
      "EPUB"
    ],
    "stage": "PARSE",
    "algorithm": "MAX_ARCHIVE_EXPANDED_BYTES",
    "parameterRefs": [
      "budgets.archiveExpandedMaxBytes"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_PARSER_LIMIT",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "EPUB.ARCHIVE_ENTRY_MAX_BYTES": {
    "id": "EPUB.ARCHIVE_ENTRY_MAX_BYTES",
    "formats": [
      "EPUB"
    ],
    "stage": "PARSE",
    "algorithm": "MAX_ARCHIVE_ENTRY_BYTES",
    "parameterRefs": [
      "budgets.archiveEntryMaxBytes"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_PARSER_LIMIT",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "EPUB.ARCHIVE_COMPRESSION_RATIO": {
    "id": "EPUB.ARCHIVE_COMPRESSION_RATIO",
    "formats": [
      "EPUB"
    ],
    "stage": "PARSE",
    "algorithm": "MAX_COMPRESSION_RATIO",
    "parameterRefs": [
      "budgets.archiveCompressionRatioMax"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_PARSER_LIMIT",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "FB2.STRUCTURE_BUDGET": {
    "id": "FB2.STRUCTURE_BUDGET",
    "formats": [
      "FB2"
    ],
    "stage": "PARSE",
    "algorithm": "MAX_FB2_STRUCTURE",
    "parameterRefs": [
      "budgets.fb2MaxDepth",
      "budgets.fb2MaxNodes",
      "budgets.fb2TextMaxBytes",
      "budgets.fb2TextMaxCharacters"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_PARSER_LIMIT",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "FB2.IMAGE_BUDGET": {
    "id": "FB2.IMAGE_BUDGET",
    "formats": [
      "FB2"
    ],
    "stage": "PARSE",
    "algorithm": "MAX_FB2_IMAGE_BYTES",
    "parameterRefs": [
      "budgets.fb2EncodedImageMaxBytes",
      "budgets.fb2DecodedImageMaxBytes",
      "budgets.fb2DecodedImagesTotalMaxBytes",
      "profiles.reflowable.embeddedImageExtensionsByMimeType"
    ],
    "action": "BLOCK_RESOURCE",
    "errorCode": "PUBLICATION_RESOURCE_BLOCKED",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "TXT.MEMORY_BUDGET": {
    "id": "TXT.MEMORY_BUDGET",
    "formats": [
      "TXT"
    ],
    "stage": "PARSE",
    "algorithm": "MAX_TXT_MEMORY",
    "parameterRefs": [
      "budgets.txtMemoryMaxBytes"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_PARSER_LIMIT",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "TXT.BOUNDED_CHUNK": {
    "id": "TXT.BOUNDED_CHUNK",
    "formats": [
      "TXT"
    ],
    "stage": "PARSE",
    "algorithm": "BOUNDED_TXT_CHUNK",
    "parameterRefs": [
      "budgets.txtChunkMaxCharacters"
    ],
    "action": "ALLOW",
    "errorCode": null,
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "PDF.DISABLE_ACTIVE_CONTENT": {
    "id": "PDF.DISABLE_ACTIVE_CONTENT",
    "formats": [
      "PDF"
    ],
    "stage": "SANITIZE",
    "algorithm": "PDF_ACTIVE_CONTENT",
    "parameterRefs": [
      "profiles.pdf.blockedActions"
    ],
    "action": "SANITIZE",
    "errorCode": null,
    "requiredConsumers": [
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "PDF.PAGE_GEOMETRY": {
    "id": "PDF.PAGE_GEOMETRY",
    "formats": [
      "PDF"
    ],
    "stage": "PARSE",
    "algorithm": "PDF_PAGE_GEOMETRY",
    "parameterRefs": [
      "budgets.pdfPageMaxCount",
      "profiles.pdf.requireFinitePageGeometry"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PDF_PAGE_LIMIT",
    "requiredConsumers": [
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "PDF.RENDER_BUDGET": {
    "id": "PDF.RENDER_BUDGET",
    "formats": [
      "PDF"
    ],
    "stage": "RENDER",
    "algorithm": "PDF_RENDER_BUDGET",
    "parameterRefs": [
      "budgets.pdfRenderMaxPixels",
      "budgets.pdfCanvasMaxDimension"
    ],
    "action": "BLOCK_RESOURCE",
    "errorCode": "PDF_RENDER_LIMIT",
    "requiredConsumers": [
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "PDF.RANGE_PROTOCOL": {
    "id": "PDF.RANGE_PROTOCOL",
    "formats": [
      "PDF"
    ],
    "stage": "DELIVERY",
    "algorithm": "PDF_RANGE_PROTOCOL",
    "parameterRefs": [
      "budgets.pdfRangeChunkBytes",
      "budgets.pdfRangeRequestMaxBytes",
      "budgets.pdfRangeMaxConcurrent",
      "budgets.pdfRangeMemoryCacheMaxBytes",
      "profiles.pdf.requireIdentityContentEncoding",
      "profiles.pdf.requireStrongRevision",
      "profiles.pdf.engineRequestLimit",
      "profiles.pdf.largeRequestAction",
      "profiles.pdf.allowWholeResponseFallback"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PDF_RANGE_INVALID",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "COMIC.PAGE_MIME": {
    "id": "COMIC.PAGE_MIME",
    "formats": [
      "CBZ",
      "ZIP",
      "CBR",
      "RAR",
      "IMAGE_DIR"
    ],
    "stage": "RESOURCE",
    "algorithm": "COMIC_PAGE_MIME",
    "parameterRefs": [
      "profiles.comic.allowedPageMimeTypes",
      "profiles.comic.pageMimeTypesByExtension"
    ],
    "action": "BLOCK_RESOURCE",
    "errorCode": "COMIC_MIME_MISMATCH",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "COMIC.ARCHIVE_STRUCTURE": {
    "id": "COMIC.ARCHIVE_STRUCTURE",
    "formats": [
      "CBZ",
      "ZIP",
      "CBR",
      "RAR"
    ],
    "stage": "PARSE",
    "algorithm": "COMIC_ARCHIVE_STRUCTURE",
    "parameterRefs": [
      "profiles.comic.archiveFatalFindings"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "COMIC_SECURITY_REJECTED",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "COMIC.PAGE_MAX_COUNT": {
    "id": "COMIC.PAGE_MAX_COUNT",
    "formats": [
      "CBZ",
      "ZIP",
      "CBR",
      "RAR",
      "IMAGE_DIR"
    ],
    "stage": "PARSE",
    "algorithm": "MAX_COMIC_PAGE_COUNT",
    "parameterRefs": [
      "budgets.comicPageMaxCount"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "COMIC_SECURITY_REJECTED",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "COMIC.ARCHIVE_BUDGET": {
    "id": "COMIC.ARCHIVE_BUDGET",
    "formats": [
      "CBZ",
      "ZIP",
      "CBR",
      "RAR",
      "IMAGE_DIR"
    ],
    "stage": "PARSE",
    "algorithm": "COMIC_ARCHIVE_BUDGET",
    "parameterRefs": [
      "budgets.comicExpandedMaxBytes",
      "budgets.comicCompressionRatioMax"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "COMIC_SECURITY_REJECTED",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "COMIC.PAGE_MAX_BYTES": {
    "id": "COMIC.PAGE_MAX_BYTES",
    "formats": [
      "CBZ",
      "ZIP",
      "CBR",
      "RAR",
      "IMAGE_DIR"
    ],
    "stage": "RESOURCE",
    "algorithm": "MAX_COMIC_PAGE_BYTES",
    "parameterRefs": [
      "budgets.comicPageMaxBytes"
    ],
    "action": "BLOCK_RESOURCE",
    "errorCode": "COMIC_PAGE_BLOCKED",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "COMIC.MANIFEST_MAX_BYTES": {
    "id": "COMIC.MANIFEST_MAX_BYTES",
    "formats": [
      "CBZ",
      "ZIP",
      "CBR",
      "RAR",
      "IMAGE_DIR"
    ],
    "stage": "DELIVERY",
    "algorithm": "MAX_COMIC_MANIFEST_BYTES",
    "parameterRefs": [
      "budgets.comicManifestMaxBytes"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "COMIC_SECURITY_REJECTED",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "COMIC.PAGE_DECODE_FAILURE": {
    "id": "COMIC.PAGE_DECODE_FAILURE",
    "formats": [
      "CBZ",
      "ZIP",
      "CBR",
      "RAR",
      "IMAGE_DIR"
    ],
    "stage": "RENDER",
    "algorithm": "COMIC_PAGE_FAILURE",
    "parameterRefs": [
      "profiles.comic.singlePageDecodeFailureAction"
    ],
    "action": "BLOCK_RESOURCE",
    "errorCode": "COMIC_PAGE_BLOCKED",
    "requiredConsumers": [
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "COMIC.MANIFEST_REVISION": {
    "id": "COMIC.MANIFEST_REVISION",
    "formats": [
      "CBZ",
      "ZIP",
      "CBR",
      "RAR",
      "IMAGE_DIR"
    ],
    "stage": "DELIVERY",
    "algorithm": "COMIC_MANIFEST_REVISION",
    "parameterRefs": [
      "profiles.comic.manifestRevisionRequired"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "COMIC_RESOURCE_CHANGED",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "AUDIO.CONTAINER_MIME": {
    "id": "AUDIO.CONTAINER_MIME",
    "formats": [
      "AUDIO",
      "AUDIOBOOK_DIR",
      "AUDIOBOOK",
      "M4B",
      "M4A",
      "MP3"
    ],
    "stage": "ADMISSION",
    "algorithm": "AUDIO_CONTAINER_MIME",
    "parameterRefs": [
      "profiles.audio.containerMimeTypes"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "AUDIO_MIME_MISMATCH",
    "requiredConsumers": [
      "BACKEND",
      "WEB"
    ]
  },
  "AUDIO.ORIGINAL_MAX_BYTES": {
    "id": "AUDIO.ORIGINAL_MAX_BYTES",
    "formats": [
      "AUDIO",
      "AUDIOBOOK_DIR",
      "AUDIOBOOK",
      "M4B",
      "M4A",
      "MP3"
    ],
    "stage": "ADMISSION",
    "algorithm": "MAX_ORIGINAL_BYTES",
    "parameterRefs": [
      "budgets.originalMaxBytes"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "PUBLICATION_TOO_LARGE",
    "requiredConsumers": [
      "BACKEND",
      "WEB"
    ]
  },
  "AUDIO.ENGINE_CODEC": {
    "id": "AUDIO.ENGINE_CODEC",
    "formats": [
      "AUDIO",
      "AUDIOBOOK_DIR",
      "AUDIOBOOK",
      "M4B",
      "M4A",
      "MP3"
    ],
    "stage": "PLAYBACK",
    "algorithm": "AUDIO_ENGINE_CODEC",
    "parameterRefs": [
      "profiles.audio.codecDecision"
    ],
    "action": "BLOCK_RESOURCE",
    "errorCode": "ENGINE_CODEC_UNSUPPORTED",
    "requiredConsumers": [
      "WEB"
    ]
  },
  "AUDIO.TRACK_AND_CHAPTER_BOUNDS": {
    "id": "AUDIO.TRACK_AND_CHAPTER_BOUNDS",
    "formats": [
      "AUDIO",
      "AUDIOBOOK_DIR",
      "AUDIOBOOK",
      "M4B",
      "M4A",
      "MP3"
    ],
    "stage": "PARSE",
    "algorithm": "AUDIO_TRACK_CHAPTER_BOUNDS",
    "parameterRefs": [
      "budgets.audioTrackMaxCount",
      "budgets.audioChapterMaxCount",
      "profiles.audio.requireOrderedTrackIdentity",
      "profiles.audio.requireFiniteNonNegativeDuration"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "AUDIO_DURATION_INVALID",
    "requiredConsumers": [
      "BACKEND",
      "WEB"
    ]
  },
  "AUDIO.METADATA_BUDGET": {
    "id": "AUDIO.METADATA_BUDGET",
    "formats": [
      "AUDIO",
      "AUDIOBOOK_DIR",
      "AUDIOBOOK",
      "M4B",
      "M4A",
      "MP3"
    ],
    "stage": "PARSE",
    "algorithm": "AUDIO_METADATA_BUDGET",
    "parameterRefs": [
      "budgets.audioMetadataMaxBytes",
      "budgets.audioArtworkMaxBytes"
    ],
    "action": "BLOCK_RESOURCE",
    "errorCode": "AUDIO_METADATA_LIMIT",
    "requiredConsumers": [
      "BACKEND",
      "WEB"
    ]
  },
  "AUDIO.REDIRECT_POLICY": {
    "id": "AUDIO.REDIRECT_POLICY",
    "formats": [
      "AUDIO",
      "AUDIOBOOK_DIR",
      "AUDIOBOOK",
      "M4B",
      "M4A",
      "MP3"
    ],
    "stage": "DELIVERY",
    "algorithm": "AUDIO_REDIRECT_POLICY",
    "parameterRefs": [
      "profiles.audio.blockedRedirectSchemes"
    ],
    "action": "REJECT_PUBLICATION",
    "errorCode": "AUDIO_SECURITY_REJECTED",
    "requiredConsumers": [
      "BACKEND",
      "WEB"
    ]
  }
} as const;
export type ReaderSafetyRule = typeof READER_SAFETY_RULES[ReaderSafetyRuleId];

export const READER_SAFETY_PLATFORM_DEFENSES = {
  "XML_EXTERNAL_ENTITY_RESOLUTION_DISABLED": {
    "id": "XML_EXTERNAL_ENTITY_RESOLUTION_DISABLED",
    "formats": [
      "EPUB",
      "FB2"
    ],
    "stage": "PARSE",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "DOCUMENT_SCRIPT_EXECUTION_DISABLED": {
    "id": "DOCUMENT_SCRIPT_EXECUTION_DISABLED",
    "formats": [
      "EPUB",
      "FB2",
      "TXT",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC"
    ],
    "stage": "RENDER",
    "requiredConsumers": [
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "DOCUMENT_INITIATED_NETWORK_DISABLED": {
    "id": "DOCUMENT_INITIATED_NETWORK_DISABLED",
    "formats": [
      "EPUB",
      "FB2",
      "TXT",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC",
      "PDF"
    ],
    "stage": "RENDER",
    "requiredConsumers": [
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "TRUSTED_RUNTIME_URI_PROVENANCE": {
    "id": "TRUSTED_RUNTIME_URI_PROVENANCE",
    "formats": [
      "EPUB",
      "FB2",
      "TXT",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC"
    ],
    "stage": "RESOURCE",
    "requiredConsumers": [
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "PDF_ACTIVE_ACTIONS_DISABLED": {
    "id": "PDF_ACTIVE_ACTIONS_DISABLED",
    "formats": [
      "PDF"
    ],
    "stage": "RENDER",
    "requiredConsumers": [
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "ORIGINAL_ARTIFACT_IMMUTABLE": {
    "id": "ORIGINAL_ARTIFACT_IMMUTABLE",
    "formats": [
      "EPUB",
      "FB2",
      "TXT",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC",
      "PDF",
      "CBZ",
      "ZIP",
      "CBR",
      "RAR",
      "IMAGE_DIR",
      "AUDIO",
      "AUDIOBOOK_DIR"
    ],
    "stage": "ADMISSION",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  },
  "NO_SECURITY_FAILURE_PARSER_FALLBACK": {
    "id": "NO_SECURITY_FAILURE_PARSER_FALLBACK",
    "formats": [
      "EPUB",
      "FB2",
      "TXT",
      "MOBI",
      "AZW",
      "AZW3",
      "PRC",
      "PDF",
      "CBZ",
      "ZIP",
      "CBR",
      "RAR",
      "IMAGE_DIR",
      "AUDIO",
      "AUDIOBOOK_DIR"
    ],
    "stage": "PARSE",
    "requiredConsumers": [
      "BACKEND",
      "WEB",
      "ANDROID",
      "IOS"
    ]
  }
} as const;
export type ReaderSafetyPlatformDefenseId = keyof typeof READER_SAFETY_PLATFORM_DEFENSES;
export type ReaderSafetyPlatformDefense = typeof READER_SAFETY_PLATFORM_DEFENSES[ReaderSafetyPlatformDefenseId];

export function readerSafetyFormatPolicy(value: string): ReaderSafetyFormatDefinition | null {
  const normalized = value.trim().toUpperCase();
  return Object.prototype.hasOwnProperty.call(READER_SAFETY_FORMATS, normalized)
    ? READER_SAFETY_FORMATS[normalized as ReaderSafetyFormat]
    : null;
}

export function requireReaderSafetyFormatPolicy(value: string): ReaderSafetyFormatDefinition {
  const policy = readerSafetyFormatPolicy(value);
  if (!policy) throw new Error(`Unsupported Reader safety format: ${value}`);
  return policy;
}

export function readerSafetyAcceptsMimeType(format: ReaderSafetyFormatDefinition, value: string): boolean {
  const normalized = value.trim().toLowerCase().split(';', 1)[0] ?? '';
  return (format.acceptedMimeTypes as readonly string[]).includes(normalized);
}

export function readerSafetyBudget(name: ReaderSafetyBudgetName): number {
  return READER_SAFETY_BUDGETS[name];
}

export function readerSafetyRule(ruleId: ReaderSafetyRuleId): ReaderSafetyRule {
  return READER_SAFETY_RULES[ruleId];
}

export function readerSafetyComicPageMimeType(extension: string): string | null {
  const normalized = extension.trim().toLowerCase();
  const mapping = READER_SAFETY_PROFILES.comic.pageMimeTypesByExtension;
  return Object.prototype.hasOwnProperty.call(mapping, normalized)
    ? mapping[normalized as keyof typeof mapping]
    : null;
}
