// Generated by packages/reader-contracts/generate-reader-progress-timing.py. Do not edit.
export const READER_PROGRESS_TIMING = {
  version: 1,
  maxUnsavedIntervalMillis: 5000,
  periodicCaptureIntervalMillis: 4000,
} as const;
