"""System composition root exports.

Runtime behavior lives in System application/infrastructure modules; this file
keeps existing process entry points stable while those dependencies are wired.
"""

from app.modules.system.infrastructure.runtime import (
    clear_system_events_with_audit,
    configured_max_event_bytes,
    create_or_reuse_health_run,
    fail_abandoned_health_runs,
    get_setting,
    health_run_snapshot,
    library_import_dashboard_snapshot,
    list_settings,
    list_system_events_page,
    maintain_system_events,
    management_overview_snapshot,
    persist_log_settings_update,
    persist_opds_settings_update,
    persist_system_setting_values,
    persist_system_settings_update,
    prepare_settings_write,
    prepare_system_event,
    prepare_system_setting_values,
    probe_database,
    prune_old_health_runs,
    prune_system_events,
    record_queue_heartbeat,
    record_system_event,
    run_system_health_checks,
    set_max_event_bytes,
    start_health_run,
    system_event_size_bytes,
    system_event_storage_view,
    upsert_setting,
    upsert_settings,
    write_prepared_settings,
    write_prepared_system_events,
)

__all__ = [
    "clear_system_events_with_audit",
    "configured_max_event_bytes",
    "create_or_reuse_health_run",
    "fail_abandoned_health_runs",
    "get_setting",
    "health_run_snapshot",
    "library_import_dashboard_snapshot",
    "list_settings",
    "list_system_events_page",
    "maintain_system_events",
    "management_overview_snapshot",
    "persist_log_settings_update",
    "persist_opds_settings_update",
    "persist_system_setting_values",
    "persist_system_settings_update",
    "prepare_settings_write",
    "prepare_system_event",
    "prepare_system_setting_values",
    "probe_database",
    "prune_old_health_runs",
    "prune_system_events",
    "record_queue_heartbeat",
    "record_system_event",
    "run_system_health_checks",
    "set_max_event_bytes",
    "start_health_run",
    "system_event_size_bytes",
    "system_event_storage_view",
    "upsert_setting",
    "upsert_settings",
    "write_prepared_settings",
    "write_prepared_system_events",
]
