import { isPublicationNavigationFormat, publicationNavigationHref } from '@shuku/reader-core';
import type { ResourceFormat } from '../../types/book';

/** Formats whose chapter units are generated by the Publication pipeline. */
export function isReflowableEbookFormat(format: string | null | undefined): format is ResourceFormat {
  return isPublicationNavigationFormat(format);
}

/** Whether a resource should render reflowable chapter navigation. */
export function hasEbookChapterNavigation(format: string | null | undefined): boolean {
  return isReflowableEbookFormat(format);
}

/**
 * Publication-owned target safe to pass as `/reader?href=`. This deliberately
 * shares the Reader Core rule used again at reader startup.
 */
export function chapterDeepLinkHref(
  format: string | null | undefined,
  href: string | null | undefined
): string | null {
  return publicationNavigationHref(format, href);
}
