import { isPublicationNavigationFormat } from '@shuku/reader-core';
import type { ResourceFormat } from '../../types/book';

/** Formats whose chapter units are generated by the Publication pipeline. */
export function isReflowableEbookFormat(format: string | null | undefined): format is ResourceFormat {
  return isPublicationNavigationFormat(format);
}

/** Whether a resource should render reflowable chapter navigation. */
export function hasEbookChapterNavigation(format: string | null | undefined): boolean {
  return isReflowableEbookFormat(format);
}
