"""Explicit query contract used by media import decisions."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

Record = dict[str, object]


class ImportLibraryQueries(Protocol):
    def copy_shelf_links_to_work(
        self, source_work_ids: list[str], target_work_id: str
    ) -> None: ...

    def count_audio_chapters_for_edition(self, edition_id: str) -> int: ...
    def count_audio_chapters_for_volume(self, volume_id: str) -> int: ...
    def count_audio_files_for_edition(self, edition_id: str) -> int: ...
    def count_audiobook_media_kind_editions(
        self, work_id: str, media_kind: str
    ) -> int: ...
    def count_editions_for_work(
        self, work_id: str, *, media_kind: str | None = None
    ) -> int: ...
    def count_primary_audiobook_editions_for_work(
        self, work_id: str, *, exclude_edition_id: str
    ) -> int: ...
    def count_visible_editions_for_work(self, work_id: str) -> int: ...
    def count_volumes_for_edition(self, edition_id: str) -> int: ...
    def delete_audio_metadata_sources(self, edition_id: str) -> None: ...
    def detach_audio_chapters_for_edition(self, edition_id: str) -> None: ...
    def detach_audio_chapters_for_edition_or_files(
        self, edition_id: str, file_ids: list[str]
    ) -> None: ...
    def existing_file_import_snapshot(self, path: Path) -> Record | None: ...
    def fail_import_assets_for_task(
        self,
        *,
        task_id: str,
        error_code: str,
        error_summary: str,
        updated_at: object,
    ) -> None: ...
    def find_audio_edition_by_version_key(
        self, version_key: str
    ) -> Record | None: ...
    def find_deferred_source_edition(
        self, *, source_path: str, work_id: str, result_edition_id: str
    ) -> Record | None: ...
    def find_edition_version_key_conflict(
        self, work_id: str, version_key: str, exclude_edition_id: str
    ) -> Record | None: ...
    def find_volume_conflict(
        self,
        edition_id: str,
        volume_index: float | None,
        volume_title: str,
    ) -> Record | None: ...
    def find_work_cover_edition(self, work_id: str) -> Record | None: ...
    def get_conversion_by_import_task_id(
        self, import_task_id: str
    ) -> Record | None: ...
    def get_edition_by_id(self, edition_id: str) -> Record | None: ...
    def get_edition_cover_path(self, edition_id: str) -> Record | None: ...
    def get_edition_format(self, edition_id: str) -> Record | None: ...
    def get_first_volume_for_edition(self, edition_id: str) -> Record | None: ...
    def get_import_asset_by_task_and_path(
        self, task_id: str, source_path: str
    ) -> Record | None: ...
    def get_import_task_by_id(self, task_id: str) -> Record | None: ...
    def get_latest_audio_tags_metadata(self, edition_id: str) -> Record | None: ...
    def get_metadata_lookup_task_id_by_import(
        self, import_task_id: str
    ) -> Record | None: ...
    def get_organize_job_for_work_edition(
        self, work_id: str, edition_id: str
    ) -> Record | None: ...
    def get_pending_import_task_for_source(
        self, source_path: str
    ) -> Record | None: ...
    def get_work_by_id(self, work_id: str) -> Record | None: ...
    def get_work_by_merge_key(self, merge_key: str) -> Record | None: ...
    def has_generated_cover_path(self, work_id: str, cover_path: str) -> bool: ...
    def list_audio_chapter_units_for_file_ordered(
        self, file_id: str
    ) -> list[Record]: ...
    def list_audio_chapters_for_edition(
        self, edition_id: str
    ) -> list[Record]: ...
    def list_audio_chapters_for_file(self, file_id: str) -> list[Record]: ...
    def list_audio_files_for_edition(self, edition_id: str) -> list[Record]: ...
    def list_audio_files_for_volume(
        self, edition_id: str, volume_id: str
    ) -> list[Record]: ...
    def list_audiobook_consumption_for_works(
        self, work_ids: list[str]
    ) -> list[Record]: ...
    def list_edition_file_paths_for_work(
        self, work_id: str, source_group_suffix: str
    ) -> list[Record]: ...
    def list_editions_by_ids(self, edition_ids: list[str]) -> list[Record]: ...
    def list_file_editions_by_paths(self, paths: list[str]) -> list[Record]: ...
    def list_library_files_by_paths(self, paths: list[str]) -> list[Record]: ...
    def list_reading_progress_for_edition(
        self, edition_id: str
    ) -> list[Record]: ...
    def list_reading_progress_for_editions(
        self, edition_ids: list[str]
    ) -> list[Record]: ...
    def list_unassigned_audio_chapters_for_edition(
        self, edition_id: str
    ) -> list[Record]: ...
    def list_visible_editions_for_work_and_format(
        self, work_id: str, fmt: str
    ) -> list[Record]: ...
    def list_volume_cover_paths_for_edition(
        self, edition_id: str
    ) -> list[Record]: ...
    def list_works_by_source_group_suffix(
        self, source_group_suffix: str
    ) -> list[Record]: ...
    def sum_audio_duration_for_edition(self, edition_id: str) -> int: ...
    def sum_audio_duration_for_volume(self, volume_id: str) -> int: ...
    def sum_audio_file_size_for_edition(self, edition_id: str) -> int: ...
    def sum_file_size_bytes_for_edition(self, edition_id: str) -> int: ...
    def sum_volume_chapter_count_for_edition(self, edition_id: str) -> int: ...
    def sum_volume_page_count_for_edition(self, edition_id: str) -> int: ...
