"""Read projections required by topology-bound media enrichment."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

Record = dict[str, object]


class ImportLibraryQueries(Protocol):
    def existing_file_import_snapshot(self, path: Path) -> Record | None: ...

    def find_work_cover_volume(self, work_id: str) -> Record | None: ...

    def get_import_asset_by_task_and_path(
        self, task_id: str, source_path: str
    ) -> Record | None: ...

    def get_import_task_by_id(self, task_id: str) -> Record | None: ...

    def get_volume_context_by_id(self, volume_id: str) -> Record | None: ...

    def get_work_by_id(self, work_id: str) -> Record | None: ...

    def has_generated_cover_path(self, work_id: str, cover_path: str) -> bool: ...

    def list_file_volumes_by_paths(self, paths: list[str]) -> list[Record]: ...

    def list_audio_volume_files(self, volume_id: str) -> list[Record]: ...

    def list_audio_volume_units(self, volume_id: str) -> list[Record]: ...

    def list_volume_cover_paths_for_version(
        self, version_id: str
    ) -> list[Record]: ...
