import { isPublicationNavigationFormat, publicationNavigationHref } from '@shuku/reader-core';
import type { ReadingFormat, WorkDetailTabKey } from '../../types/work';

/** Formats whose chapter units are generated by the Publication pipeline. */
export function isReflowableEbookFormat(format: string | null | undefined): format is ReadingFormat {
  return isPublicationNavigationFormat(format);
}

/** Whether a classified media tab should render reflowable chapter navigation. */
export function hasEbookChapterNavigation(
  detailTab: WorkDetailTabKey | null | undefined,
  format: string | null | undefined
): boolean {
  return detailTab !== null && detailTab !== undefined && detailTab !== 'STRUCTURE'
    && isReflowableEbookFormat(format);
}

/**
 * Publication-owned target safe to pass as `/reader?href=`. This deliberately
 * shares the Reader Core rule used again at reader startup.
 */
export function chapterDeepLinkHref(
  format: string | null | undefined,
  href: string | null | undefined
): string | null {
  return publicationNavigationHref(format, href);
}
