"""SQLAlchemy model package — import all models so Base.metadata is complete."""

from __future__ import annotations

from app.models.auth import (
    PasswordResetToken,
    ReaderBookmark,
    Session,
    User,
    UserLibraryAccess,
    UserPreference,
)
from app.models.import_pipeline import (
    BookConversionTask,
    DownloadTask,
    ImportAsset,
    ImportLog,
    ImportScanJob,
    ImportTask,
    ImportWorkItem,
    KindleSendTask,
    Source,
    SourceSearchRecord,
)
from app.models.library import (
    ExternalMetadataCache,
    Library,
    LibraryFacet,
    LibraryFile,
    LibraryMediaVersion,
    LibraryMetadata,
    LibraryOperation,
    LibraryReadingProgress,
    LibraryReadingUnit,
    LibraryVersion,
    LibraryVolume,
    LibraryVolumeFacet,
    LibraryWork,
    LibraryWorkFacet,
    MediaVersionMigrationEvent,
    ReaderProgressMutation,
    WorkDetailPreference,
)
from app.models.organize import (
    DuplicateCandidate,
    MetadataLookupTask,
    MetadataOpfQueueState,
    MetadataProviderExecution,
    MetadataProviderPipeline,
    MetadataSuggestion,
    MetadataWritebackOperation,
    MetadataWritebackPreparation,
    MetadataWritebackTarget,
    OrganizeJob,
    OrganizePolicy,
    OrganizeRun,
)
from app.models.settings import (
    BookIdentityCache,
    QueueControlOperation,
    QueueRuntimeState,
    ReaderBookPreference,
    ReaderPreference,
    ReaderProgressCursor,
    SystemEvent,
    SystemHealthRun,
    SystemSetting,
)
from app.models.shelf import Shelf, ShelfWork
from app.modules.publications.infrastructure.models import (
    PublicationNavigationCache,
)
from app.modules.shelf.infrastructure.models import ShelfCollectionMembership

__all__ = [
    "BookConversionTask",
    "BookIdentityCache",
    "DownloadTask",
    "DuplicateCandidate",
    "ExternalMetadataCache",
    "ImportAsset",
    "ImportLog",
    "ImportScanJob",
    "ImportTask",
    "ImportWorkItem",
    "KindleSendTask",
    "Library",
    "LibraryFacet",
    "LibraryFile",
    "LibraryMediaVersion",
    "LibraryMetadata",
    "LibraryOperation",
    "LibraryReadingProgress",
    "LibraryReadingUnit",
    "LibraryVersion",
    "LibraryVolume",
    "LibraryVolumeFacet",
    "LibraryWork",
    "LibraryWorkFacet",
    "MediaVersionMigrationEvent",
    "MetadataLookupTask",
    "MetadataOpfQueueState",
    "MetadataProviderExecution",
    "MetadataProviderPipeline",
    "MetadataSuggestion",
    "MetadataWritebackOperation",
    "MetadataWritebackPreparation",
    "MetadataWritebackTarget",
    "OrganizeJob",
    "OrganizePolicy",
    "OrganizeRun",
    "PasswordResetToken",
    "PublicationNavigationCache",
    "QueueControlOperation",
    "QueueRuntimeState",
    "ReaderBookPreference",
    "ReaderBookmark",
    "ReaderPreference",
    "ReaderProgressCursor",
    "ReaderProgressMutation",
    "Session",
    "Shelf",
    "ShelfCollectionMembership",
    "ShelfWork",
    "Source",
    "SourceSearchRecord",
    "SystemEvent",
    "SystemHealthRun",
    "SystemSetting",
    "User",
    "UserLibraryAccess",
    "UserPreference",
    "WorkDetailPreference",
]
