"""Pure catalog topology domain contracts."""

from app.modules.catalog.domain.admission import (
    ARCHIVE_SOURCE_FORMATS,
    AUDIO_SOURCE_FORMATS,
    DIRECT_FILE_SOURCE_FORMATS,
    SYSTEM_NOISE_NAMES,
    AdmissionEvidence,
    AdmissionRejectionReason,
    ArchiveEvidence,
    AudioCodec,
    AudioEvidence,
    BundleEvidence,
    DirectFileEvidence,
    PrimaryEvidence,
    SourceAdmissionEvidence,
    SourceAdmissionRejection,
    SourceAdmissionResult,
    is_system_noise_name,
    parse_disc_component,
)
from app.modules.catalog.domain.layouts import interpret_layout
from app.modules.catalog.domain.model import (
    AdmissionKind,
    AssetCandidate,
    EntryType,
    LayoutResult,
    LayoutViolation,
    OrganizationMode,
    PathComparison,
    ProbedEntry,
    SidecarRole,
    SourceFormat,
    SourceKind,
    ViolationCode,
    VolumeCandidate,
)

__all__ = [
    "ARCHIVE_SOURCE_FORMATS",
    "AUDIO_SOURCE_FORMATS",
    "DIRECT_FILE_SOURCE_FORMATS",
    "SYSTEM_NOISE_NAMES",
    "AdmissionEvidence",
    "AdmissionKind",
    "AdmissionRejectionReason",
    "ArchiveEvidence",
    "AssetCandidate",
    "AudioCodec",
    "AudioEvidence",
    "BundleEvidence",
    "DirectFileEvidence",
    "EntryType",
    "LayoutResult",
    "LayoutViolation",
    "OrganizationMode",
    "PathComparison",
    "PrimaryEvidence",
    "ProbedEntry",
    "SidecarRole",
    "SourceAdmissionEvidence",
    "SourceAdmissionRejection",
    "SourceAdmissionResult",
    "SourceFormat",
    "SourceKind",
    "ViolationCode",
    "VolumeCandidate",
    "interpret_layout",
    "is_system_noise_name",
    "parse_disc_component",
]
