import { READER_FONT_FAMILY_OPTIONS } from '@shuku/reader-core';
export {
  READER_THEME_OPTIONS,
  READER_FONT_SIZE_OPTIONS,
  READER_LINE_HEIGHT_OPTIONS,
  READER_FONT_FAMILY_OPTIONS,
  READER_FLOW_OPTIONS,
  READER_SPREAD_MODE_OPTIONS,
  READER_FONT_WEIGHT_OPTIONS,
  READER_LETTER_SPACING_OPTIONS,
  READER_PAGE_MARGIN_OPTIONS,
  READER_PROGRESS_STYLE_OPTIONS,
  READER_COMIC_FLOW_OPTIONS,
  READER_PAGE_GAP_OPTIONS,
  READER_PAGE_TURN_ANIMATION_OPTIONS,
  READER_COMIC_IMAGE_FIT_OPTIONS,
  READER_COMIC_IMAGE_VARIANT_OPTIONS,
  READER_COMIC_DIRECTION_OPTIONS,
  READER_PDF_FIT_OPTIONS,
  READER_TAP_ZONE_OPTIONS,
  READER_TEXT_ALIGN_OPTIONS,
  READER_PARAGRAPH_INDENT_OPTIONS,
  READER_PARAGRAPH_SPACING_OPTIONS,
  READER_PDF_ROTATION_OPTIONS,
  READER_PDF_CROP_OPTIONS
} from '@shuku/reader-core';

export type ReaderFontFamily = typeof READER_FONT_FAMILY_OPTIONS[number]['value'];
